### ISSUE TITLE
ValueError, TypeError, etc

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#11]
Hi,

Thanks for the great tool. I was just messing around with a test and control sample.

Commands:
```
tombo resquiggle --overwrite --processes 16 --align-processes 8 --include-event-stdev \
        --minimap2-executable ~/data/software/minimap2/minimap2/minimap2 \
        test_fast5dir/ \
        ref.fasta

tombo resquiggle --overwrite --processes 16 --align-processes 8 --include-event-stdev \
        --minimap2-executable ~/data/software/minimap2/minimap2/minimap2 \
        control_fast5dir/ \
        ref.fasta

tombo test_significance --fast5-basedirs test_fast5dir/ \
    --control-fast5-basedirs control_fast5dir/\
    --statistics-file-basename compare \
    --minimum-test-reads 1

```

It throws the following error:
```
Parsing tombo index file(s).
Performing two-sample comparison significance testing.
Parsing tombo index file(s).
Performing significance testing across 930 regions. (Will print a dot for each batch completed)
Process Process-2:
Traceback (most recent call last):
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1374, in _test_signif_worker
    ctrl_reg_reads, kmer_ref, upstrm_bases, alt_ref, alt_base)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1270, in get_region_stats
    r_stats, r_poss = get_read_comp_stats(r_data, ctrl_means, ctrl_sds)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1108, in get_read_comp_stats
    r_means, read_start, read_end = comp_clip_and_flip()
ValueError: need more than 2 values to unpack```

I think this traces back to Line 1065 in https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_stats.py

...where it returns 2 Nones:
``` return None, None ```
when 3 values are expected....

If I add a 3rd None -- it seems to move on to a new error:
```
Traceback (most recent call last):
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1375, in _test_signif_worker
    ctrl_reg_reads, kmer_ref, upstrm_bases, alt_ref, alt_base)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1270, in get_region_stats
    r_stats, r_poss = get_read_comp_stats(r_data, ctrl_means, ctrl_sds)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1109, in get_read_comp_stats
    r_z_scores = get_read_comp_z_score(r_means, read_start, read_end)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1091, in get_read_comp_z_score
    r_means - ctrl_means[read_start-reg_start+fm_offset:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```


Any ideas on how to proceed?

Best,

  John

**Comment by JohnUrban** [comment]
Well the formatting in my above comment is a bit messed up -- and I cannot seem to edit it. It also isn't letting me preview for some reason.... so here it is again...hopefully fixed:


Hi,

Thanks for the great tool. I was just messing around with a test and control sample.

Commands:
```
tombo resquiggle --overwrite --processes 16 --align-processes 8 --include-event-stdev \
        --minimap2-executable ~/data/software/minimap2/minimap2/minimap2 \
        test_fast5dir/ \
        ref.fasta

tombo resquiggle --overwrite --processes 16 --align-processes 8 --include-event-stdev \
        --minimap2-executable ~/data/software/minimap2/minimap2/minimap2 \
        control_fast5dir/ \
        ref.fasta

tombo test_significance --fast5-basedirs test_fast5dir/ \
    --control-fast5-basedirs control_fast5dir/\
    --statistics-file-basename compare \
    --minimum-test-reads 1

```

It throws the following error:
```
Parsing tombo index file(s).
Performing two-sample comparison significance testing.
Parsing tombo index file(s).
Performing significance testing across 930 regions. (Will print a dot for each batch completed)
Process Process-2:
Traceback (most recent call last):
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1374, in _test_signif_worker
    ctrl_reg_reads, kmer_ref, upstrm_bases, alt_ref, alt_base)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1270, in get_region_stats
    r_stats, r_poss = get_read_comp_stats(r_data, ctrl_means, ctrl_sds)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1108, in get_read_comp_stats
    r_means, read_start, read_end = comp_clip_and_flip()
ValueError: need more than 2 values to unpack
```

I think this traces back to Line 1065 in https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_stats.py

...where it returns 2 Nones:
``` 
return None, None 
```
when 3 values are expected....

If I add a 3rd None -- it seems to move on to a new error:
```
Traceback (most recent call last):
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1375, in _test_signif_worker
    ctrl_reg_reads, kmer_ref, upstrm_bases, alt_ref, alt_base)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1270, in get_region_stats
    r_stats, r_poss = get_read_comp_stats(r_data, ctrl_means, ctrl_sds)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1109, in get_read_comp_stats
    r_z_scores = get_read_comp_z_score(r_means, read_start, read_end)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1091, in get_read_comp_z_score
    r_means - ctrl_means[read_start-reg_start+fm_offset:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```


Any ideas on how to proceed?

Best,

  John

**Comment by marcus1487** [comment]
Thank you for the bug report. I have actually started to refactor this bit of code internally as these `None` returns are not really pythonic (leading to these types of issues).

As for a quick fix for you to continue, the following patch should help:
```python
diff --git a/tombo/tombo_stats.py b/tombo/tombo_stats.py
index 1e99bfd..a440fbd 100644
--- a/tombo/tombo_stats.py
+++ b/tombo/tombo_stats.py
@@ -1106,6 +1106,8 @@ def get_region_stats(
             return r_pvals, r_poss
 
         r_means, read_start, read_end = comp_clip_and_flip()
+        if r_means is None:
+            return None, None
         r_z_scores = get_read_comp_z_score(r_means, read_start, read_end)
 
         if np.sum(np.logical_not(np.isnan(r_z_scores))) == 0:
```

I will include a more complete fix in the next release. Let me know if this solves the problem for now.

**Comment by JohnUrban** [comment]
Hi Marcus,

Your patch gets it to work if I already have the ```return None, None``` changed to ```return None, None, None``` at line 1065.

Starting from scratch, this patch gets it to work:
```
diff --git a/tombo/tombo_stats.py b/tombo/tombo_stats.py
index 1e99bfd..3d54e12 100644
--- a/tombo/tombo_stats.py
+++ b/tombo/tombo_stats.py
@@ -1062,7 +1062,7 @@ def get_region_stats(
         def comp_clip_and_flip():
             r_means, _ = th.get_read_means_and_seq(r_data)
             if r_means is None:
-                return None, None
+                return None, None, None
 
             read_start, read_end = r_data.start, r_data.end
             if read_start + fm_offset < reg_start:
@@ -1106,6 +1106,8 @@ def get_region_stats(
             return r_pvals, r_poss
 
         r_means, read_start, read_end = comp_clip_and_flip()
+	if r_means is None:
+	    return None, None
         r_z_scores = get_read_comp_z_score(r_means, read_start, read_end)
 
         if np.sum(np.logical_not(np.isnan(r_z_scores))) == 0:
```

What I am now seeing:
```
Parsing tombo index file(s).
Performing two-sample comparison significance testing.
Parsing tombo index file(s).
Performing significance testing across 930 regions. (Will print a dot for each batch completed)
...................................................................................................
````

Thanks for your help.
