### ISSUE TITLE
detect modifications h5py error

### ISSUE THREAD

**Issue by noamharel161** [nanoporetech/tombo#115]
Hello,
I am running tombo on python 3.4, installed through bioconda.
After running resquiggle successfully, tried to run detect_modifications and got the following error:

tombo detect_modifications alternative_model --fast5-basedirs fast5/pass/0/ --statistics-file-basename sample.alt_modified_base_detection --per-read-statistics-basename sample.alt_modified_base_detection --alternate-bases 5mC --processes 1
[13:28:00] Parsing Tombo index file(s).
[13:28:00] Performing alternative model testing.
[13:28:00] Performing alternative model testing against 5mC model.
[13:28:00] Performing modified base detection across genomic regions.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:53<00:00, 53.34s/it]
Process Process-3:
Traceback (most recent call last):
  File "/Users/taliakustin/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/Users/taliakustin/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/taliakustin/miniconda2/lib/python2.7/site-packages/tombo/tombo_stats.py", line 3459, in _get_stats_queue
    all_stats.close()
  File "/Users/taliakustin/miniconda2/lib/python2.7/site-packages/tombo/tombo_stats.py", line 2302, in close
    self._close_write()
  File "/Users/taliakustin/miniconda2/lib/python2.7/site-packages/tombo/tombo_stats.py", line 2294, in _close_write
    self.chrm_id_grp.attrs[chrm_name] = chrm_id
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/taliakustin/miniconda2/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/Users/taliakustin/miniconda2/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 202, in create
    if h5a.exists(self._id, self._e(name)):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 100, in h5py.h5a.exists
ValueError: No attribute name (no attribute name)

Anyone had experience with this?
Thank you.

**Comment by marcus1487** [comment]
I see 2 issues here. The first is related to issue #114, and has to do with how the per-read statistics file is formatted. A fix for this issue is coming soon. For now, leaving off the per-read statistics output should resolve this issue. 

The second point is that this error appears to be coming from a python2 installation of the h5py package. I would recommend re-installing h5py within your python 3.4 environment. This should resolve this issue as well.
