### ISSUE TITLE
Some motifs can't be identified

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#127]
Hi:
     when I used `tombo plot motif_with_stats`with`--motif`parameter,some motifs can be correctly identified(like AAACA,AAACT,...).However,some other motifs can't be identified(like GAACA,GGACA,GGACC,GGACT ...)
```
Traceback (most recent call last):
  File "/home/weir/anaconda3/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2314, in plot_main
    plot_motif_centered_signif(*base_args, **kwargs)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2028, in plot_motif_centered_signif
    motif.motif_len + context_width - 1):
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/tombo_stats.py", line 2832, in iter_stat_seqs
    stat_seq = genome_index.get_seq(chrm, start, end)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/tombo_helper.py", line 818, in get_seq
    'Encountered invalid genome sequence request.')
tombo.tombo_helper.TomboError: Encountered invalid genome sequence request.
```

**Comment by marcus1487** [comment]
I have just pushed a patch to fix this issue. The issue actually did not have to do with the motif passed, but from where significant regions were being queried. This bug was hit whenever a region close to the edge of a chromosome boundary was encountered and an attempt was made to extract the sequence outside of a sequence record. In any case an install from the github repo should fix this issue (and will be included in the next release).

**Comment by marctormo** [comment]
Hello Marcus,
I'm getting the same error with "tombo text_output signif_sequence_context " and I'm already working with v1.5 (I also reinstalled tombo from github:
Traceback (most recent call last):
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/lib/python3.5/site-packages/tombo/__main__.py", line 271, in main
    _text_output_commands._write_signif_diff_main(args)
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/lib/python3.5/site-packages/tombo/_text_output_commands.py", line 474, in _write_signif_diff_main
    args.num_bases, args.statistics_filename)
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/lib/python3.5/site-packages/tombo/_text_output_commands.py", line 407, in write_most_signif
    p_int.add_seq(genome_index)
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/lib/python3.5/site-packages/tombo/tombo_helper.py", line 1920, in add_seq
    self.chrm, self.start, self.end))
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/lib/python3.5/site-packages/tombo/tombo_helper.py", line 818, in get_seq
    'Encountered invalid genome sequence request.')
tombo.tombo_helper.TomboError: Encountered invalid genome sequence request.

Thanks!

**Comment by marcus1487** [comment]
This looks as though the github version may not be the one called. Line 1920 in the current code is not the one making the call to `add_seq` noted in the second to last error line. You could try to uninstall all versions of tombo and then reinstall to ensure that the github version is installed.

**Comment by marctormo** [comment]
Thanks Marcus,

I uninstalled and installed again from github. Now the error is in the line 1918:
[09:41:53] Loading statistics from file.
Traceback (most recent call last):
  File "/homes/aplic/noarch/software/Python/3.5.2-foss-2016b/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo', 'console_scripts', 'tombo')()
  File "/gpfs42/robbyfs/homes/users/manager/tombo/tombo/__main__.py", line 271, in main
    _text_output_commands._write_signif_diff_main(args)
  File "/gpfs42/robbyfs/homes/users/manager/tombo/tombo/_text_output_commands.py", line 474, in _write_signif_diff_main
    args.num_bases, args.statistics_filename)
  File "/gpfs42/robbyfs/homes/users/manager/tombo/tombo/_text_output_commands.py", line 407, in write_most_signif
    p_int.add_seq(genome_index)
  File "/gpfs42/robbyfs/homes/users/manager/tombo/tombo/tombo_helper.py", line 1918, in add_seq
    self.chrm, self.start, self.end))
  File "/gpfs42/robbyfs/homes/users/manager/tombo/tombo/tombo_helper.py", line 818, in get_seq
    'Encountered invalid genome sequence request.')
tombo.tombo_helper.TomboError: Encountered invalid genome sequence request.

**Comment by marctormo** [comment]
Hi Marcus,
Have you checked this issue? It only happens with 6mA (with 5mC works fine)

Thanks

**Comment by marcus1487** [comment]
Just pushed a fix for this second related issue. Pull from github and let me know if this issue is resolved for you.

**Comment by marctormo** [comment]
Hi Marcus,
It worked, thank you very much!
