### ISSUE TITLE
write_wiggles TypeError when not including fast5_dirs

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#13]
This is just a heads-up more than anything.

If I run this command:

```
tombo write_wiggles --statistics-filename compare.tombo.stats --wiggle-types fraction
```

...as suggested on the main github page:
https://github.com/nanoporetech/tombo#text-output-wiggle-file-format

I get this error:

```
Loading statistics from file.
Parsing tombo index file(s).
Traceback (most recent call last):
  File "/gpfs/data/sgerbi/jurban/software/albacore/tombo/git/tombo/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.1', 'console_scripts', 'tombo')()
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/__main__.py", line 163, in main
    text_output_commands.wiggle_main(args)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/text_output_commands.py", line 286, in wiggle_main
    args.wiggle_types)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/text_output_commands.py", line 163, in write_all_wiggles
    f5_dirs1, corrected_group, basecall_subgroups)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/tombo_helper.py", line 472, in parse_fast5s
    for fast5s_dir in fast5_basedirs:
TypeError: 'NoneType' object is not iterable
```

If I add paths to the test and control fast5 dirs, it seems to work (I get wiggles to look at):

```
tombo write_wiggles --fast5-basedirs ../data/NB02 --control-fast5-basedirs ../data/NB04 --statistics-filename compare.tombo.stats --wiggle-types fraction
```

Output to screen:
```
Loading statistics from file.
Parsing tombo index file(s).
Parsing tombo index file(s).
Writing wiggles.
Parsing statistics.
Writing statistics wig(s).
```

Feel free to close.

**Comment by marcus1487** [comment]
Ah yes. This is an issue actually. There is no reason to require the fast5 directories simply to output the stats wiggle. This just needs to be handled correctly. Thanks for the bug report. I'll have this fixed in the next release.

**Comment by JohnUrban** [comment]
Excellent.
