### ISSUE TITLE
plot_per_read TypeError 

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#14]
Hi Marcus,

Again - this is more of a heads-up than anything.

On some genomic locations, this command fails:
```
tombo plot_per_read --plot-standard-model --genome-locations NC_000913.3:2325816 --num-bases 42 --fast5-basedirs data/NB04 --pdf-filename tombo_results.per_read_stats.wthStdModel.pdf
```

With this error:
```
Parsing per read modifications at genome locations.
Parsing tombo index file(s).
Using default canonical ***** DNA ***** model.
Preparing plot data.
Traceback (most recent call last):
  File "/gpfs/data/sgerbi/jurban/software/albacore/tombo/git/tombo/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.1', 'console_scripts', 'tombo')()
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/__main__.py", line 168, in main
    plot_commands.plot_main(args)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 2035, in plot_main
    plot_per_read_mods_genome_location(*base_args, **kwargs)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 1422, in plot_per_read_mods_genome_location
    fm_lag, num_reads, box_center)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 1191, in plot_per_read_modification
    read_rows=True, num_reads=num_reads)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 350, in get_reg_events
    for r_data in reg_reads if strand is None or r_data.strand == strand]
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 342, in get_read_reg_events
    int_start - r_data.start:int_end - r_data.start]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I don't have a solution or suggestion yet. If I have the time to track it down, I will let you know. If it is meaningful, this only seems to happen when I point ```--fast5-basedirs``` to a control directory -- though it doesn't always happen, and that observation may be irrelevant.

Feel free to close.

Best,

  John

**Comment by marcus1487** [comment]
I believe this is fixed by adding this line `if r_means is None: return None ` at the beginning of the `get_read_reg_events` function, right after the `r_means = th.get_read_base_means(r_data)` line.

I am wondering, as a larger issue, what may be the result of all of these issues. Are you by any chance running the `resquiggle` command with the `--skip-index` flag?  I ask because each of these issues boils down to attempting to access re-squiggle data from a fast5 file that does not contain that data. This should not happen since all files included in the tombo index file should have been successfully re-squiggled. This is actually pointing me to some test cases that I should certainly add, but just trying to track down why exactly you are running into these issues. 

Thanks again for all the bug reports!

**Comment by JohnUrban** [comment]
That is a negative on the ```--skip-index```.

Here is the command I ran:
```
tombo resquiggle --overwrite --processes 16 --align-processes 8 --include-event-stdev \
	--minimap2-executable ~/data/software/minimap2/minimap2/minimap2 \
	NB0${SLURM_ARRAY_TASK_ID}/ \
	ecoli.fasta 
```

**Comment by JohnUrban** [comment]
The extra line of code worked.

Here is the patch:
```
diff --git a/tombo/plot_commands.py b/tombo/plot_commands.py
index 1a433b8..e1459ac 100644
--- a/tombo/plot_commands.py
+++ b/tombo/plot_commands.py
@@ -314,6 +314,8 @@ def get_read_correction_data(
 
 def get_read_reg_events(r_data, int_start, int_end):
     r_means = th.get_read_base_means(r_data)
+    if r_means is None:
+        return None
     if r_data.start > int_start and r_data.end < int_end:
         # handle reads that are contained in a region
         start_overlap = int_end - r_data.start
```

**Comment by JohnUrban** [comment]
As far as what happened upstream in ```resquiggle``` that is connecting all these issues goes, the following may be irrelevant, but maybe not.

This was the output of ```resquiggle``` for the test sample:
```
Getting file list.
Estimating global scale parameter
Correcting 21689 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).
..........................................
Failed reads summary (8119 total failed):
	Alignment not produced (if all reads failed check for index files) :	1725
	No valid path found through raw signal of long read :	3401
	No valid path found through raw signal of short read :	62
	No valid path found through start of raw signal :	1758
	Read event to sequence alignment extends beyond --bandwidth :	990
	Read sequence from SAM and cooresponding cigar string do not agree. :	92
	Too little signal around event-aligned genomic deletion :	81
	Too much raw signal for short mapped sequence :	10
```

And for the control sample:
```
Getting file list.
Estimating global scale parameter
Correcting 10834 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).
.....................
Failed reads summary (3363 total failed):
	Alignment not produced (if all reads failed check for index files) :	682
	No valid path found through raw signal of long read :	1410
	No valid path found through raw signal of short read :	37
	No valid path found through start of raw signal :	721
	Read event to sequence alignment extends beyond --bandwidth :	395
	Read sequence from SAM and cooresponding cigar string do not agree. :	61
	Too little signal around event-aligned genomic deletion :	56
	Too much raw signal for short mapped sequence :	1
```

Are those high failure rates or what?

**Comment by marcus1487** [comment]
Those are a bit high. Is this R9.4/5 data? The default model may not handle R9 data very well.

And as long as there was no actual error (with stack trace) the index file should still only point to correctly re-squiggled files. That is really the part that I would like to get to the heart of.

**Comment by JohnUrban** [comment]
This is indeed R9.4/5 data.

There was no actual error.

The search continues....
