### ISSUE TITLE
Plotting errors when loading digest.so

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/tombo#145]
Hi there,

I have trouble running plotting command on a slurm server :

```
tombo plot motif_with_stats --fast5-basedirs /bactos_reads/fast5/    --motif GATC --genome-fasta ../bactos.genome.fasta    --statistics-filename bactos.alternative_model_testing.6mA.tombo.stats    --pdf-filename bactos.alternative_model_testing.6mA_GATC.pdf
```

```
[13:11:35] Loading statistics from file.
[13:11:36] Parsing Tombo index file(s).
[13:11:45] Finding most signficant regions with motif.
[13:11:45] Getting all regions statistics.
[13:11:47] Preparing plot data.
[13:11:58] Plotting.
/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/tools/R/R-3.4.3_bis/R-3.4.3/lib64/R/library/digest/libs/digest.so':
  /tools/R/R-3.4.3_bis/R-3.4.3/lib64/R/library/digest/libs/digest.so: undefined symbol: R_NilValue
```
... followed with related errors

```
warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.5', 'console_scripts', 'tombo')()
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2314, in plot_main
    plot_motif_centered_signif(*base_args, **kwargs)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2081, in plot_motif_centered_signif
    stat_locs, overplot_thresh, pdf_fn, std_ref, alt_ref)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/_plot_commands.py", line 1547, in plot_motif_centered_with_stats
    SignalData, BasesData, StatsData, ModelData)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  impossible de charger l'objet partagé '/tools/R/R-3.4.3_bis/R-3.4.3/lib64/R/library/digest/libs/digest.so':
  /tools/R/R-3.4.3_bis/R-3.4.3/lib64/R/library/digest/libs/digest.so: undefined symbol: R_NilValue
```

Last time gridExtra library was not installed so I dealed with it but digest was already there and loading it manually works. 

Hoping that you can point out what could be the source of this error. 
Thanks,

Paul

**Comment by marcus1487** [comment]
This certainly looks like a library linking issue with R and rpy2. Can you run the command: `python -c "import rpy2; from rpy2 import robjects; from rpy2.robjects.packages import importr"`. The failure of this command generally points to the source of these issues.

**Comment by pterzian** [comment]
As you said there were issues with the rpy2 package. I don't know much more detail but our cluster admin did a new installation and it works fine now.
Thanks for your answer.
