### ISSUE TITLE
plot_motif_with_stats TypeError

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#15]
Hello once again,

Obviously I am trying out all the fun Tombo sub-commands today, so apologies for the bombardment of issues. This one again is just to bring to your attention more than anything else. 

This command:
```
tombo plot_motif_with_stats --fast5-basedirs data/NB02 --motif $MOTIF --statistics-filename compare.tombo.stats --pdf-filename motif_with_stats.pdf
```

...is failing with this error:
```
Loading statistics from file.
Parsing tombo index file(s).
Finding signficant regions with motif.
Preparing plot data.
********** WARNING *********
	Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled and that all data slot corresponding accordingly.
Traceback (most recent call last):
  File "/gpfs/data/sgerbi/jurban/software/albacore/tombo/git/tombo/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.1', 'console_scripts', 'tombo')()
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/__main__.py", line 168, in main
    plot_commands.plot_main(args)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 2006, in plot_main
    plot_motif_centered_signif(*base_args, **kwargs)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 1789, in plot_motif_centered_signif
    stat_locs, overplot_thresh, pdf_fn, not stat_order, tb_model_fn)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 1096, in plot_motif_centered_with_stats
    BasesData = get_base_r_data(merged_reg_data)
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/plot_commands.py", line 546, in get_base_r_data
    for i, base in enumerate(reg_data.seq):
TypeError: 'NoneType' object is not iterable
```

I ran it again to see if it would go through -- reasoning that perhaps this had something to do with random sampling of reads. Nonetheless, it failed again with the same error.
It doesn't always fail though -- e.g.  when I ran it with a control fast5 dir it went through (twice).

Example 1:
```
tombo plot_motif_with_stats --fast5-basedirs data/NB02 --control-fast5-basedirs data/NB04 --motif $MOTIF --statistics-filename compare.tombo.stats --pdf-filename motif_with_stats_2.pdf

Loading statistics from file.
Parsing tombo index file(s).
Parsing tombo index file(s).
Finding signficant regions with motif.
Preparing plot data.
********** WARNING *********
	Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled and that all data slot corresponding accordingly.
Plotting.
```

Example 2:
```
tombo plot_motif_with_stats --num-context 4 --num-regions 10 --fast5-basedirs data/NB02 --control-fast5-basedirs data/NB04 --motif $MOTIF --statistics-filename compare.tombo.stats --pdf-filename motif_with_stats_3.pdf

Loading statistics from file.
Parsing tombo index file(s).
Parsing tombo index file(s).
Finding signficant regions with motif.
Preparing plot data.
********** WARNING *********
	Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled and that all data slot corresponding accordingly.
********** WARNING *********
	Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled and that all data slot corresponding accordingly.
Plotting.
```

Again - I don't have a solution or suggestion yet. If I have the time to track it down, I will report back.

Feel free to close.

**Comment by JohnUrban** [comment]
As a side note, in my hands, using the motif GGGGG makes it hang forever:
```
Loading statistics from file.
Parsing tombo index file(s).
Finding signficant regions with motif.
```
It has been on that last step for a couple hours when everything else finished in 5-20 minutes.

**Comment by marcus1487** [comment]
For the first issue, this is a bug that occurs in the `tombo_helper.py` script. Here is a patch to fix this issue:

```
diff --git a/tombo/tombo_helper.py b/tombo/tombo_helper.py
index 6da0c08..7c91c9a 100644
--- a/tombo/tombo_helper.py
+++ b/tombo/tombo_helper.py
@@ -1213,6 +1213,8 @@ def get_region_reads(
     no_cov_regions = [
         (len(reg_data.reads) == 0, str(reg_data.chrm) + ':' + str(reg_data.start))
         for reg_data in all_reg_data]
+    if add_seq:
+        all_reg_data = add_reg_seq(all_reg_data)
     if not filter_no_cov:
         return all_reg_data
 
@@ -1226,9 +1228,6 @@ def get_region_reads(
             '; '.join([reg for no_cov, reg in no_cov_regions
                        if no_cov]) + '\n')
 
-    if add_seq:
-        all_reg_data = add_reg_seq(all_reg_data)
-
     return all_reg_data
 
 def get_region_sequences(
```

Again I will include this fix in the next release.

For the GGGGG motif plotting command, this is likely due to the querying of many files in order to search for the GGGGG motif in the sequence. As the genomic sequence is stored in each reads file in the tombo data a fasta file is not required. The genomic sequence is obtained from a close to minimal set of reads for each location, but this can still be quite expensive. The sequence is extracted from each genomic location in order of statistical testing value, so it is also likely that the GGGGG motif does not contain many significant results and thus has to obtain sequence from many locations.

This is certainly a target for optimization at some point. I should probably add the option to pass a FASTA genome file here in order to speed up the sequence lookup.

**Comment by JohnUrban** [comment]
Thanks for the feedback. Passing a FASTA genome file sounds like a good idea for future releases.
