### ISSUE TITLE
Error in API of tombo

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#160]
Hi marcus:
I ran the following code in accordance with the official documentation guide.
```
from tombo import tombo_helper, tombo_stats, resquiggle
reg_data = tombo_helper.intervalData(chrm='chr20', start=10000, end=10100, strand='+')
reads_index = tombo_helper.TomboReads(['test_data/native_reads',])
reg_base_levels = reg_data.add_reads(reads_index).get_base_levels(num_reads=10)
```
An error occurred on the last line of the code:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/tombo_helper.py", line 2021, in get_base_levels
    return np.column_stack(reg_events)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 353, in column_stack
    return _nx.concatenate(arrays, 1)
ValueError: need at least one array to concatenate
```
I don't think these two objects (reads_index,reg_data) having flaw.Here is related information:
```
>>> reg_data
<tombo.tombo_helper.intervalData object> :
           chrm : AT1G42970.1
          start : 1556
            end : 1606
         strand : +
         reg_id : None
       reg_text : ""
          reads : <332 reads>
            seq : None
>>> reads_index
<tombo.tombo_helper.TomboReads object at 0x2b5a09fd7eb8>
```
Could you give me a hand?
thanks!

**Comment by weir12** [comment]
I've solved this problem by upgrading the version of numpy
