### ISSUE TITLE
multi_to_single_fast5 stops converting after first two fast5 files

### ISSUE THREAD

**Issue by kychen37** [nanoporetech/tombo#171]
Hello!

I am trying to convert my fast5 files into single-read fast5 files to be used in tombo. Every time I've tried running this command ```multi_to_single_fast5 --input_path fast5_pass/ --save_path single_reads/ --recursive``` it gives me this error regarding the progress bar right away:

```
/ 0 of 10|                                                                                                                                                                             |N/A% ETA:  --:--:--Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/kchen/programs/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/kchen/programs/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/pool.py", line 486, in _handle_results
    cache[job]._set(i, obj)
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/pool.py", line 662, in _set
    self._callback(self._value)
  File "/home/kchen/programs/anaconda3/lib/python3.7/site-packages/ont_fast5_api/conversion_tools/multi_to_single_fast5.py", line 36, in update
    pbar.update(pbar.currval + 1)
AttributeError: 'ProgressBar' object has no attribute 'currval'
```

Then it freezes here for several hours before I inevitably stop the process, at which point it gives me this error:
```
^CTraceback (most recent call last):
  File "/home/kchen/programs/anaconda3/bin/multi_to_single_fast5", line 10, in <module>
Process ForkPoolWorker-1:
    sys.exit(main())
  File "/home/kchen/programs/anaconda3/lib/python3.7/site-packages/ont_fast5_api/conversion_tools/multi_to_single_fast5.py", line 112, in main
    batch_convert_multi_files_to_single(args.input_path, args.save_path, args.threads, args.recursive)
  File "/home/kchen/programs/anaconda3/lib/python3.7/site-packages/ont_fast5_api/conversion_tools/multi_to_single_fast5.py", line 49, in batch_convert_multi_files_to_single
    pool.join()
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/pool.py", line 556, in join
    self._worker_handler.join()
  File "/home/kchen/programs/anaconda3/lib/python3.7/threading.py", line 1032, in join
Traceback (most recent call last):
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
    self._wait_for_tstate_lock()
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/home/kchen/programs/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/connection.py", line 398, in _send_bytes
    self._send(buf)
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
KeyboardInterrupt
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kchen/programs/anaconda3/lib/python3.7/multiprocessing/pool.py", line 585, in _terminate_pool
    "Cannot have cache with result_hander not alive")
AssertionError: Cannot have cache with result_hander not alive
```

Each time I've tried  this command, it will convert the first two fast5 files into single reads (each in their directories names '0' and '1' within 'single_reads') but seems to freeze there. I've also tried splitting up the mulit-read fast5 files into smaller batches of 10 files at a time, but it still freezes after the first two and gives the same errors. Can someone help me figure out what's wrong? Thank you!

**Comment by marcus1487** [comment]
I am not sure what is causing this error. As this is an issue with the `ont_fast5_api` software and not `tombo` posting to the issues page there may give more advice on resolving this issue.
