### ISSUE TITLE
Error when running plot roc 

### ISSUE THREAD

**Issue by Beez93** [nanoporetech/tombo#175]
Hi,
i'm trying to run the plot roc command (tombo plot roc --statistics-filenames de_novo.all.tombo.stats alt_model.All.5mC.tombo.stats alt_model.All.6mA.tombo.stats --motif-descriptions 'CCWGG:2:5mC de novo::GATC:2:6mA de novo' 'CCWGG:2:5mC alt model' 'GATC:2:6mA alt model' )
and i got this error : 
[10:12:53] Parsing motifs.
[10:12:53] Parsing genome.
Traceback (most recent call last):
  File "/env/cns/home/bd/.local/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo', 'console_scripts', 'tombo')()
  File "/env/export/bigtmp1/bd/tombo/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/env/export/bigtmp1/bd/tombo/tombo/_plot_commands.py", line 2344, in plot_main
    plot_roc(**kwargs)
  File "/env/export/bigtmp1/bd/tombo/tombo/_plot_commands.py", line 118, in plot_roc
    genome_index = th.Fasta(fasta_fn)
  File "/env/export/bigtmp1/bd/tombo/tombo/tombo_helper.py", line 778, in __init__
    self.fasta_fn = resolve_path(fasta_fn)
  File "/env/export/bigtmp1/bd/tombo/tombo/tombo_helper.py", line 368, in resolve_path
    return os.path.realpath(os.path.expanduser(fn_path))
  File "/env/ig/soft/ig/python-3.3.2/el6-x86_64-generic/lib/python3.3/posixpath.py", line 252, in expanduser
    if not path.startswith(tilde):
AttributeError: 'NoneType' object has no attribute 'startswith'

Any idea of what the problem could be here ?

**Comment by marcus1487** [comment]
The conditionally required command line argument enforcement for this command is not correct. I will add a fix to provide a more useful error message.

The root problem though is that a reference FASTA is required in order to plot a roc curve given a set of motifs. If you provide the `--genome-fasta` argument, that should bypass this issue.

**Comment by Beez93** [comment]
Effectively it works now. 
Thanks
