### ISSUE TITLE
tombo plot

### ISSUE THREAD

**Issue by calvincicha** [nanoporetech/tombo#182]
Hello, I recently generated the top 100 locations of potential modification in my genome using the tombo pipeline. I am now trying to make the graphs of these regions using the tombo plot motif_with_stats command. While running this command I am getting the below error. Does anyone have any advice on what this error means and how to resolve it.

tombo plot motif_with_stats --fast5-basedirs /home/calvinc/Desktop/single_combined_fast5 --motif GTCACCCAGGGTAAT --genome-fasta /home/calvinc/Desktop/MS2_Genome_Sequence.fasta --statistics-filename Balrog_total_files.tombo.stats --pdf-filename Balrog_total_files.pdf
Traceback (most recent call last):
  File "/software/miniconda3/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/software/miniconda3/lib/python3.6/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/software/miniconda3/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2314, in plot_main
    plot_motif_centered_signif(*base_args, **kwargs)
  File "/software/miniconda3/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2010, in plot_motif_centered_signif
    genome_index = th.Fasta(fasta_fn)
  File "/software/miniconda3/lib/python3.6/site-packages/tombo/tombo_helper.py", line 785, in __init__
    self.index = pyfaidx.Faidx(self.fasta_fn)
  File "/software/miniconda3/lib/python3.6/site-packages/pyfaidx/__init__.py", line 423, in __init__
    self.build_index()
  File "/software/miniconda3/lib/python3.6/site-packages/pyfaidx/__init__.py", line 594, in build_index
    raise e
  File "/software/miniconda3/lib/python3.6/site-packages/pyfaidx/__init__.py", line 587, in build_index
    bad_lines[0][0] + 1))
pyfaidx.FastaIndexingError: Line length of fasta file is not consistent! Inconsistent line found in >NC_001417.2 at line 52.

**Comment by marcus1487** [comment]
This appears to be an issue with `pyfaidx` handling a particular variant of a FASTA file. It seems to have been resolved [here](https://github.com/mdshw5/pyfaidx/issues/83). Could you try to upgrade you `pyfaidx` installation and re-run the command (or follow the suggested fix for the FASTA file in that discussion)?

**Comment by marcus1487** [comment]
Has this resolved your issue?

**Comment by calvincicha** [comment]
I fixed this errror an alternative way. From the link you send it appears that this error was occurring because the last line in my fasta genome file was not completely to the end (in line with the above lines). I just added some fake bases to that line to make it complete. Probably not the best fix, but it worked.
