### ISSUE TITLE
Error in output statistic file

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#188]
Hi @marcus1487 
When I run the following command:`tombo text_output browser_files --fast5-basedirs  <my.fast5files> --control-fast5-basedirs <my.control.files> --statistics-filename  level_sample_compare.tombo.stats --genome-fasta  <my.transcriptome.files > --file-types statistic`
I got such error:
```
[10:09:07] Parsing Tombo index file(s).
[10:10:19] Parsing Tombo index file(s).
[10:11:16] Loading statistics from file.
[10:11:22] Parsing and outputting statistics wiggles.
Traceback (most recent call last):
  File "/home/weir/anaconda3/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/__main__.py", line 269, in main
    _text_output_commands._browser_files_main(args)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/_text_output_commands.py", line 457, in _browser_files_main
    args.motif_descriptions)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/_text_output_commands.py", line 383, in write_all_browser_files
    VCOV_WIG_TYPE in wig_types, motif_descs, fasta_fn)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/_text_output_commands.py", line 206, in write_frac_wigs
    if do_stats: curr_stats.append(all_stats._stat_transform(block_stats))
  File "/home/weir/anaconda3/lib/python3.6/site-packages/tombo/tombo_stats.py", line 3168, in <lambda>
    pos_stat[self._stat_slot])
FloatingPointError: divide by zero encountered in log10
```
In the previous step：`tombo detect_modifications level_sample_compare` I added `--fishers-method-context 0 --store-p-value --num-most-significant-stored  1000000  --statistic-type  ks`  options and parameters
here is screenshot of statistics file in HDFview.Maybe that gives some useful information.
 ![image](https://user-images.githubusercontent.com/37523816/59576122-12e49880-90f1-11e9-969f-4026d72df202.png)

**Comment by weir12** [comment]
To figure out what is wrong in my statistics file,I ran the `tomb text_output signif_sequence_context` command and I got the same error.It seems that such a zero value causes an error.
![image](https://user-images.githubusercontent.com/37523816/59583179-1be36300-910d-11e9-973a-5cd924232bff.png)

**Comment by marcus1487** [comment]
A fix has been pushed to resolve this issue. A re-install using `pip install git+https://github.com/nanoporetech/tombo.git` should resolve this issue.
