### ISSUE TITLE
OSError: Can't read data (inflate() failed)

### ISSUE THREAD

**Issue by MarkusHaak** [nanoporetech/tombo#201]
Hi,

resquiggle failed on my current dataset with >1,600,000 reads with the following Traceback:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run self._target(*self._args, **self._kwargs)
  File "~/python3_venv/lib64/python3.7/site-packages/tombo/resquiggle.py", line 1636, in _io_and_mappy_thread_worker obs_filter, index_q, q_score_thresh, sig_match_thresh, std_ref)
  File "~/python3_venv/lib64/python3.7/site-packages/tombo/resquiggle.py", line 1386, in _io_and_map_read all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "~/python3_venv/lib64/python3.7/site-packages/h5py-2.9.0-py3.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 573, in __getitem__ self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (inflate() failed)
```
Unfortunately, I do not know the fast5 file that triggers the error. I therefore checked the integrity of all fast5 containers with h5_validate, deleted some reads that could not be read at all, but the error remained. It leads to tombo beeing blocked since a worker process will not return.

Therefore, I updated to the latest tombo version and added another try block to line 1935 in resquiggle.py:

```
    try:
        all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
    except:
        raise th.TomboError(
            'Cannot read raw signal data ' +
            '(inflate() probably failed)')
```

I will report if this fixes the problem.

Best,
Markus

**Comment by marcus1487** [comment]
This looks like a reasonable solution. Did this edit fix your issue?

**Comment by MarkusHaak** [comment]
Yes, it did fix the issue! And thanks to the option to output which reads failed during resquiggling and why, I also know which read caused the problem.

**Comment by cgjosephlee** [comment]
Hi @marcus1487 ,
can we have this fix merged into master branch? I still have this problem in latest release. Resquiggle will never end and no index file is generated, until I found this issue.

**Comment by marcus1487** [comment]
This fix has been pushed to master.
