### ISSUE TITLE
Error in tombo detect_modifications level_sample_compare

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#209]
Hi marcus:
This error occurred when I ran the following command:
`tombo detect_modifications level_sample_compare --fast5-basedirs fast5_dir --statistics-file-basename sample1_sample2 --alternate-fast5-basedirs another_fast5_dir --statistic-type  ks --store-p-value --processes 16 --minimum-test-reads 50 --fishers-method-context 0`
```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/root/anaconda3/lib/python3.7/site-packages/tombo/tombo_stats.py", line 4324, in compute_group_reg_stats
    samp_cov = np.logical_not(np.isnan(samp_base_levels)).sum(axis=1)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
and
```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/root/anaconda3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/root/anaconda3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/root/anaconda3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```
Can you give me a hand?

**Comment by marcus1487** [comment]
This appears to be from an older version of the code as the line numbers noted in the error do not correspond to the most recent version. Could you try to update to the most recent github code and try to run this command again?

**Comment by weir12** [comment]
Resolved,thanks

**Comment by weir12** [comment]
Hi,marcus:
After tombob was updated, a new problem arose:

```
Process Process-1:
Traceback (most recent call last):
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4338, in compute_group_reg_stats
    end=reg_data.end + fm_offset).get_base_levels()
  File "/home/weir/software/tombo/tombo/tombo_helper.py", line 2029, in get_base_levels
    r_means = get_read_reg_events(r_data)
  File "/home/weir/software/tombo/tombo/tombo_helper.py", line 1997, in get_read_reg_events
    -end_overlap:start_overlap]
ValueError: could not broadcast input array from shape (598) into shape (594)
```

**Comment by marcus1487** [comment]
I have pushed a fix for this issue. Let me know if this does not resolve this issue.

**Comment by weir12** [comment]
Thank you for your support,but unfortunately problems remain.
```
Traceback (most recent call last):
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4338, in compute_group_reg_stats
    end=reg_data.end + fm_offset).get_base_levels()
  File "/home/weir/software/tombo/tombo/tombo_helper.py", line 2024, in get_base_levels
    r_means = get_read_reg_events(r_data)
  File "/home/weir/software/tombo/tombo/tombo_helper.py", line 1994, in get_read_reg_events
    r_data.end - self.start] = r_means
ValueError: could not broadcast input array from shape (347) into shape (343)
```

**Comment by marcus1487** [comment]
I'm having trouble reproducing this error. Was this data perhaps resquiggled with a previous version of tombo? Could you try to re-run the `tombo resquiggle` command and then re-run this `detect_modifications` command to help diagnose this issue.

**Comment by weir12** [comment]
Thanks,I have noticed that all the errors are aroused by a specific `fast5_fn` which is `re-squiggled` by old version tombo.I will solve this problem by `re-squiggle` with `--overwrite`

**Comment by weir12** [comment]
HI @marcus1487 :
The problem remained,after updating tombo to the latest version by git and` re-squiggle ` all involved` fast5_fn`.
```
[10:47:41] Parsing Tombo index file(s).
[10:48:01] Performing two-sample group comparison significance testing.
[10:48:01] Parsing Tombo index file(s).
[10:48:38] Calculating read coverage regions.
[10:48:38] Calculating read coverage.
[10:48:44] Calculating read coverage.
Process Process-3:
Traceback (most recent call last):
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4344, in compute_group_reg_stats
    samp_cov = np.logical_not(np.isnan(samp_base_levels)).sum(axis=1)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[10:49:13] Performing modified base detection across genomic regions.
  0%|                                                                      | 0/27460 [00:00<?, ?it/s]Process Process-1:
Traceback (most recent call last):
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/home/weir/software/tombo/tombo/tombo_stats.py", line 4344, in compute_group_reg_stats
    samp_cov = np.logical_not(np.isnan(samp_base_levels)).sum(axis=1)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by marcus1487** [comment]
Hi @weir12 ,

This appears to be a new issue. Tracing back this section of code I am unable to find a reason for these errors and I have not come across this particular error myself. Could you check that you have an up-to-date installation of h5py and numpy linked to this installation of tombo. After updating h5py this may require `resquiggle` to be re-run.
