### ISSUE TITLE
plot kmer failure

### ISSUE THREAD

**Issue by cathoderaymission** [nanoporetech/tombo#212]
Command line:
tombo plot kmer --fast5-basedirs  dir --pdf-filename dir.kmer-plot.pdf

```
[16:45:38] Parsing Tombo index file(s).
[16:46:09] Extracting read levels.
[17:04:50] Preparing plot data.
Traceback (most recent call last):     
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 361, in from_object      
    mv = memoryview(obj)                                                        
TypeError: memoryview: a bytes-like object is required, not 'tuple' 
                                                    
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py3/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.5', 'console_scripts', 'tombo')()
  File "/home/py3/lib64/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64
.egg/tombo/__main__.py", line 279, in main                         
    _plot_commands.plot_main(args)
  File "/home/py3/lib64/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64
.egg/tombo/_plot_commands.py", line 2357, in plot_main
    plot_kmer_dist(*base_args, **kwargs) 
  File "/home/py3/lib64/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64
.egg/tombo/_plot_commands.py", line 488, in plot_kmer_dist
    'Read':r.StrVector(plot_r_ids)})
  File "/home/py3/lib64/python3.7/site-packages/rpy2/robjects/vectors.py", line 
379, in __init__
    super().__init__(obj)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", li
ne 288, in __init__
    super().__init__(type(self).from_object(obj).__sexp__)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", li
ne 365, in from_object
    res = cls.from_iterable(obj)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/conversion.p
y", line 28, in _
    cdata = function(*args, **kwargs)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", li
ne 314, in from_iterable
    cast_in)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", li
ne 239, in _populate_r_vector
    set_elt(r_vector, i, cast_value(v))
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", li
ne 424, in _as_charsxp_cdata
    return conversion._str_to_charsxp(x)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/conversion.p
y", line 120, in _str_to_charsxp
    cchar = _str_to_cchar(val)
  File "/home/py3/lib64/python3.7/site-packages/rpy2/rinterface_lib/conversion.p
y", line 99, in _str_to_cchar
    b = s.encode(encoding)
```

This is using the 1.5 release.

I'm using rpy2 version 3.0.5 from the pip repository.

**Comment by cathoderaymission** [comment]
Per bug #208 I replaced rpy2 with version 2.9 and everything worked fine, so clearly this is a change in the newer version of rpy2 again.

Note: R gives a package warning for plot kmer where the "gridExtra" package needs to be installed for the color distribution at the bottom of the plot, otherwise it just shows the kmer letters.

**Comment by marcus1487** [comment]
Thank you for reporting this issue and the resulting fix (downgrading to rpy2<3). Given this and #208, it sounds as though it would be best to pin the rpy2 requirement to rpy2<3 instead of playing whack-a-mole with these rpy2>=3 issues. I will push this update shortly.
