### ISSUE TITLE
Preprocessing steps are failing for tombo

### ISSUE THREAD

**Issue by jolespin** [nanoporetech/tombo#222]
Below is the command I ran.  I've been having some difficulties getting `tombo` to run.  I'm essentially looking for methylation signals on my assembly from `flye`.  I've followed the documentation but each time it has errored out (sidenote: the program hangs after erroring and does not have an exit code)

First I tried running `resquiggle`:
```
(flye_env) -bash-4.1$ tombo resquiggle --processes 4 --num-most-common-errors 5 --overwrite ${FAST5} ${ASSEMBLY}

[11:31:40] Loading minimap2 reference.
[11:31:45] Getting file list.
[11:48:55] Loading default canonical ***** DNA ***** model.
[11:48:56] Re-squiggling reads (raw signal to genomic sequence alignment).
5 most common unsuccessful read types (approx. %):
   100.2% ( 117397 reads) : Fastq slot not present in --basecall-group
     -----
     -----
     -----
     -----
```

Second I tried `tombo preprocess annotate_raw_with_fastqs`:
```
(flye_env) -bash-4.1$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir Sequencing/fast5 --fastq-filenames Sequencing/20180907_1957_V195_JIRA1224.pass.all.fastq.gz --overwrite --processes 4
[15:34:17] Preparing reads and extracting read identifiers.
  0%|          | 0/392122 [00:00<?, ?it/s]/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
100%|██████████| 392122/392122 [1:49:45<00:00, 59.54it/s]
[17:28:10] Annotating FAST5s with sequence from FASTQs.
  0%|          | 0/392122 [00:00<?, ?it/s]Process Process-7:
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py", line 148, in _feed_seq_records_worker
    fastq_rec = list(islice(fastq_fp, 4))
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Both of these commands fail and hang...

**What is the expected output?** 
**What is the input structure of the fast5 directory?** 
**Is there a way to get jobs to error out with an exit code?**

**Comment by marcus1487** [comment]
For the first `resquiggle` command, it looks like the reads are not annotated with the basecall information. Given this status this is the expected output for the `resquiggle` command.

For the `preprocess` command, the first warnings are new to me, but appear to be due to an update to the `h5py` package. These should not effect processing. The error for the second command appears to be due to the input fastqs being gzipped. The preprocessing command only takes uncompressed fastq files. The preprocess command should work if the fastq files are uncompressed.

**Comment by jolespin** [comment]
Thank you, I got it to work I believe. 

```
(base) -bash-4.1$ cat cmd_preprocessing.sh
FAST5="Sequencing/fast5/"
ASSEMBLY="Assembly/flye_output/assembly.fasta"
FASTQ="Sequencing/20180907_1957_V195_JIRA1224.pass.all.fastq"
N_JOBS=24


qsub -l himem -cwd -P 0709 -N run_preprocessing -pe threaded ${N_JOBS} -M jespinoz@jcvi.org -m e -j y "source activate flye_env && tombo resquiggle --processes ${N_JOBS} --overwrite --dna ${FAST5} ${ASSEMBLY} && tombo preprocess annotate_raw_with_fastqs  --overwrite --processes ${N_JOBS} --fast5-basedir ${FAST5} --fastq-filenames ${FASTQ}"
```

Resulting in the following output:

```
(base) -bash-4.1$ cat run_preprocessing.o10671498
[15:11:36] Loading minimap2 reference.
[15:11:41] Getting file list.
[15:17:37] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|██████████| 392122/392122 [8:52:28<00:00, 12.27it/s]
[00:10:05] Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 392122 total reads):
   100.0% ( 392122 reads) : Fastq slot not present in --basecall-group
[00:10:06] Saving Tombo reads index to file.
[00:10:08] Preparing reads and extracting read identifiers.
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
100%|██████████| 392122/392122 [27:28<00:00, 237.93it/s]
[00:41:08] Annotating FAST5s with sequence from FASTQs.
 75%|███████▌  | 295980/392122 [11:27<03:43, 430.42it/s]
[00:52:36] Added sequences to a total of 295980 reads.
******************** WARNING ********************
	Not all read ids from FAST5s or sequencing summary files were found in FASTQs.
		This can result from reads that failed basecalling or if full sets of FAST5s/sequence summaries are not processed with full sets of FASTQs.
```

However, when I run the next command:

```
qsub -cwd -P 0709 -N run_detect -pe threaded ${N_JOBS} -M jespinoz@jcvi.org -m e -j y "source activate flye_env && tombo detect_modifications de_novo --fast5-basedirs ${FAST5} --statistics-file-basename pt_nanopore --processes ${N_JOBS}"
```

I get the following error.  Is this a fatal error with tombo hanging or is this expected:
```
[10:13:09] Parsing Tombo index file(s).
******************** WARNING ********************
	Failed to parse tombo index file for Sequencing/fast5/ directory. Creating temporary index from FAST5 files.
```

**Comment by marcus1487** [comment]
The `preprocess` command should be run before the `resquiggle` command. This is why the `resquiggle` command is still showing that all reads fail due to no Fastq data present.
