### ISSUE TITLE
`ValueError: need more than 3 values to unpack` when running `tombo text_output browser_files`

### ISSUE THREAD

**Issue by jolespin** [nanoporetech/tombo#224]
Why does `signal` and `signal_sd` throw the following error: `ValueError: need more than 3 values to unpack`?

Right now, it appears to be running for the others.

#### Script
```
FAST5="Sequencing/fast5/"
ASSEMBLY="Assembly/flye_output/assembly.fasta"
FASTQ="Sequencing/20180907_1957_V195_JIRA1224.pass.all.fastq"
ALT="CpG"

OUT_DIR=tombo_output/${ALT}
BASENAME=${OUT_DIR}/pt_nanopore

tombo text_output browser_files --fast5-basedirs ${FAST5}  --statistics-filename ${OUT_DIR}/pt_nanopore.${ALT}.tombo.stats --file-types coverage valid_coverage fraction dampened_fraction  dwell  statistic signal signal_sd --browser-file-basename ${OUT_DIR}/pt_nanopore"
```
#### Output

```
CpG
[15:14:58] Parsing Tombo index file(s).
[15:15:02] Parsing and outputting signal means and differences.
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/__main__.py", line 269, in main
    _text_output_commands._browser_files_main(args)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_text_output_commands.py", line 457, in _browser_files_main
    args.motif_descriptions)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_text_output_commands.py", line 358, in write_all_browser_files
    group_name, SIG_WIG_TYPE in wig_types, False)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/flye_env/lib/python2.7/site-packages/tombo/_text_output_commands.py", line 270, in write_signal_and_diff_wigs
    reads_index, chrm_sizes, SIG_SLOT, ctrl_reads_index):
ValueError: need more than 3 values to unpack
```

**Comment by marcus1487** [comment]
This appears very similar to this issue #130 . Can you install from the current github version to see if this fixes the error?

**Comment by jolespin** [comment]
The current version I'm using is `v1.5` installed via conda (https://anaconda.org/bioconda/ont-tombo):

```
(flye_env) -bash-4.1$ tombo --version
Tombo version: 1.5
```

Which looks like it's the same version as the GitHub version:  https://github.com/nanoporetech/tombo/blob/master/tombo/_version.py


Is the GitHub build different?  If so, I'll try reinstalling and seeing if it helps.  Thanks!

**Comment by marcus1487** [comment]
The last release was 1.5, but I have not bumped the version since. A number of fixes have been applied to the github codebase since this release, so a patch release is due. I will try to a new release put together shortly.

Until then you can install directly from github via `pip install git+https://github.com/nanoporetech/tombo.git`. This may require uninstalling the current version as the version number has not been bumped.

**Comment by marcus1487** [comment]
New version pushed to pypi and request made to update conda package.
