### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#238]
Hi
Recently I've been working with some old re-squiggled folders(It was sequenced two years ago and Used tombo for resquiggle in half a year ago).
When I used `tombo detect_modifications de_novo` for analyzed .Some trouble was happened in a part of fast5 files.
```
[15:47:48] Parsing Tombo index file(s).
[15:48:11] Performing de novo model testing against canonical model.
[15:48:11] Calculating read coverage regions.
[15:48:11] Calculating read coverage.
Process Process-12:
[15:48:21] Performing modified base detection across genomic regions.
  0%|                                                       | 4/31807 [00:00<13:20, 39.74it/s]Traceback (most recent call last):
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/weir/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weir/anaconda3/lib/python3.7/site-packages/tombo/tombo_stats.py", line 4420, in _test_signif_worker
    use_standard_llhr, per_read_q, stat_type, prior_weights)
  File "/home/weir/anaconda3/lib/python3.7/site-packages/tombo/tombo_stats.py", line 4205, in compute_reg_stats
    r_data, std_ref, fm_offset, reg_data)
  File "/home/weir/anaconda3/lib/python3.7/site-packages/tombo/tombo_stats.py", line 3860, in compute_de_novo_read_stats
    read_start, read_end, read_id) = de_novo_clip_and_flip()
  File "/home/weir/anaconda3/lib/python3.7/site-packages/tombo/tombo_stats.py", line 3803, in de_novo_clip_and_flip
    with h5py.File(r_data.fn, 'r') as fast5_data:
  File "/home/weir/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/weir/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
  0%|                                                    | 28/31807 [00:11<3:39:51,  2.41it/s]Process Process-4:
  0%|                                                    | 32/31807 [00:13<3:35:34,  2.46it/s]
```
I'm not sure if there are some corruptions of my files or an incompatible version(tombo h5py hdf5 etc).
So I started  re-squiggle them
```
5 most common unsuccessful read types (approx. %):                                            
     7.0% (    276 reads) : Poor raw to expected signal matching (revert with `tombo filter cl
ear_filters`)   40 reads) : Error closing fast5 file                                          
     3.4% (    134 reads) : Error opening or writing to fast5 file                            
                35 reads) : Base calls not found in FAST5 (see `tombo preprocess`)            
     2.7% (    107 reads) : Alignment not produced                                            
                                                         
     1.0% (     40 reads) : Error closing fast5 file                                                        
     0.9% (     35 reads) : Base calls not found in FAST5 (see `tombo preprocess`)                          
  0%|          | 3958/1732710 [02:57<21:35:08, 22.25it/s]
```
There were some unusual errors which a number of  internal error in the fast5 files.
That wrong folder is  integrated from multiple folders which are well re-squiggled.
Is there any way to fix corruption files?
Thanks!

**Comment by marcus1487** [comment]
This certainly does look like an issue with corrupt FAST5 files. I am not aware of a robust method to fix corrupted FAST5 files. I would generally recommend that files to be processed with tombo be copied since the files are being edited and thus some file corruption can happen. You might try to convert the files to multi and then back to single using the ont_fast5_api, but I can't be certain this will help.

**Comment by weir12** [comment]
marcus,thanks.We have confirmed that this is file corrupted event caused by a hard disk failure.
