### ISSUE TITLE
tombo "detect_modifications aggregate_per_read_stats" issue

### ISSUE THREAD

**Issue by Kennefick** [nanoporetech/tombo#246]
Hi Marcus, 

I am receiving the following error when running the "tombo detect_modifications aggregate_per_read_stats" command:

tombo detect_modifications aggregate_per_read_stats --per-read-statistics-filename tombo.per_read_stats --statistics-filename location_per_read_stats --single-read-threshold 0.5 --processes 18 --corrected-group RawGenomeCorrected
[09:00:06] Loading and aggregating per-read statistics.
  0%|                                                   | 0/896 [00:00<?, ?it/s]Process Process-8:
Traceback (most recent call last):
  File "/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/software/tombo/1.5-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64.egg/tombo/tombo_stats.py", line 4694, in _agg_stats_worker
    stat_type, reg_poss)
  File "/software/tombo/1.5-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64.egg/tombo/tombo_stats.py", line 4091, in apply_per_read_thresh
    for pos in stat_locs]
  File "/software/tombo/1.5-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64.egg/tombo/tombo_stats.py", line 4091, in <listcomp>
    for pos in stat_locs]
TypeError: argument of type 'NoneType' is not iterable
Process Process-12:
Traceback (most recent call last):
  File "/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/software/tombo/1.5-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64.egg/tombo/tombo_stats.py", line 4694, in _agg_stats_worker
    stat_type, reg_poss)
  File "/software/tombo/1.5-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64.egg/tombo/tombo_stats.py", line 4091, in apply_per_read_thresh
    for pos in stat_locs]
  File "/software/tombo/1.5-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/ont_tombo-1.5-py3.7-linux-x86_64.egg/tombo/tombo_stats.py", line 4091, in <listcomp>
    for pos in stat_locs]
TypeError: argument of type 'NoneType' is not iterable

The error message continues as above, I haven't pasted the whole thing as it is very long and seems to just be repeating a similar problem e.g with the "site-packages" and "multiprocessing". 

Please let me know if you require any further info. 

Kind regards, 

Jack

**Comment by marcus1487** [comment]
This error seems to indicate an invalid per-read statistics file. Is there a chance that this is an HDF5 file, but not the per-read statistics file? Or is this a per-read statistics file from an older version of Tombo?

**Comment by Kennefick** [comment]
Hi Marcus, 

I have used the per-read statistics files for the tombo plot per_read and they work fine for that. They were generated recently using Tombo 1.5. 

kind regards, 

Jack
