### ISSUE TITLE
Error while using --overplot Boxplot

### ISSUE THREAD

**Issue by nemitheasura** [nanoporetech/tombo#289]
Hi, 
I encountered an error while running tombo plot with --overplot Boxplot. Other plotting commands worked perfectly fine. 

I passed this command:
tombo plot most_significant --fast5-basedirs /my/fast5/dir --control-fast5-basedirs /my/control/fast5/dir --statistics-filename my.tombo.stats --overplot-type Boxplot 

And it resulted in following error:

/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error: Can't draw more than one boxplot per group. Did you forget aes(group = ...)?
Run `rlang::last_error()` to see where the error occurred.

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/software/tombo/1.5.1/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.5.1', 'console_scripts', 'tombo')()
  File "/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/tombo/_plot_commands.py", line 2343, in plot_main
    plot_most_signif(*base_args, **kwargs)
  File "/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/tombo/_plot_commands.py", line 2027, in plot_most_signif
    plot_two_samples(
  File "/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/tombo/_plot_commands.py", line 1414, in plot_two_samples
    r.globalenv[str('plotGroupComp')](
  File "/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error: Can't draw more than one boxplot per group. Did you forget aes(group = ...)?
Run `rlang::last_error()` to see where the error occurred.

As far as I know this error is caused by ggplot2 update. There is a thread on StackOverflow regarding this:
https://stackoverflow.com/questions/57192727/getting-an-error-that-ggplot2-3-2-0-cant-draw-more-than-one-boxplot-per-group

According to this, my colleague fixed the problem by editing /usr/local/software/tombo/1.5.1/lib/python3.8/site-packages/tombo/R_scripts/plotGroupComp.R - in line 41 he added  ,group=interaction(Position + 0.5,Group),

I hope this will be helpful for other users.

**Comment by marcus1487** [comment]
As this project has only limited support currently, I would recommend downgrading the ggplot2 version to fix this issue. Mixing the python and R+ggplot2 for plotting is one reason for the eventual deprecation of Tombo. This combination is far too likely to lead to issues such as this. We are working to provide a more robust replacement for Tombo at some point and will address issues such as this there.
