### ISSUE TITLE
unexpected_tombo_errors.892.err with tombo resquiggle

### ISSUE THREAD

**Issue by q1134269149** [nanoporetech/tombo#296]
Hi, 
   I used tombo to resquiggle my data, and I got a error as following:
**1) nohup.tombo.log:**
_nohup: ignoring input
[00:52:55] Loading minimap2 reference.
[00:53:07] Getting file list.
[01:17:50] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|██████████| 968143/968143 [78:04:35<00:00,  3.44it/s]
******************** WARNING ********************
        Unexpected errors occured. See full error stack traces for first (up to) 50 errors in "unexpected_tombo_errors.892.err"
[07:22:28] Final unsuccessful reads summary (6.5% reads unsuccessfully processed; 63302 total reads):
     4.5% (  43303 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     1.8% (  17217 reads) : Alignment not produced
     0.3% (   2780 reads) : Read event to sequence alignment extends beyond bandwidth
     0.0% (      1 reads) : Unexpected error
     0.0% (      1 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
[07:22:28] Saving Tombo reads index to file.
**********************end_of_resquiggle************_

2) **unexpected_tombo_errors.892.err:**
_BaseCalled_template:::/home/qinh/multi_to_single_f5/161/be540142-d694-43ea-b0d2-33888ec79303.fast5
:::
Traceback (most recent call last):
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/tombo_helper.py", line 94, in banded_traceback
    return c_banded_traceback(*args, **kwargs)
  File "tombo/_c_dynamic_programming.pyx", line 305, in tombo._c_dynamic_programming.c_banded_traceback
NotImplementedError: Read event to sequence alignment extends beyond bandwidth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1575, in _resquiggle_worker
    map_res, rsqgl_params, fast5_fn, all_raw_signal)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1491, in run_rsqgl_iters
    seq_samp_type=seq_samp_type)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1168, in resquiggle_read
    seq_samp_type=seq_samp_type, reg_id=map_res.align_info.ID)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1038, in find_adaptive_base_assignment
    rsqgl_params.band_bound_thresh)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/tombo_helper.py", line 96, in banded_traceback
    raise TomboError(unicode(e))
tombo.tombo_helper.TomboError: Read event to sequence alignment extends beyond bandwidth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1583, in _resquiggle_worker
    map_res, save_params, fast5_fn, all_raw_signal)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1491, in run_rsqgl_iters
    seq_samp_type=seq_samp_type)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1168, in resquiggle_read
    seq_samp_type=seq_samp_type, reg_id=map_res.align_info.ID)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 1028, in find_adaptive_base_assignment
    fwd_pass, fwd_pass_move, band_event_starts, shifted_z_scores = run_fwd_pass()
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 899, in run_fwd_pass
    mapped_start_offset, rsqgl_params, events_per_base)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 676, in _get_masked_start_fwd_pass
    shifted_z_scores[seq_pos,:] = get_start_mask_z_score(seq_pos, event_pos)
  File "/home/qinh/anaconda2/envs/py3/lib/python3.6/site-packages/tombo/resquiggle.py", line 661, in get_start_mask_z_score
    event_vals, r_ref_means[seq_pos], r_ref_sds[seq_pos],
IndexError: index 412 is out of bounds for axis 0 with size 412_

**I wonder if this mistake will affect my subsequent analysis? And how I should resolve this error? 
Thanks
hqin**

**Comment by marcus1487** [comment]
This error occurs only on a single read and will likely not effect your downstream analysis.

**Comment by q1134269149** [comment]
> This error occurs only on a single read and will likely not effect your downstream analysis.

Thanks.
