### ISSUE TITLE
Empty numpy array for level_sample_compare KS test

### ISSUE THREAD

**Issue by Chris-Kimmel** [nanoporetech/tombo#303]
I've run into a new Tombo issue that I can't find anything about on Google. My setup is a little complex since the job was submitted by Snakemake; I'll share what I've got now while I work on a minimal working example.

This is a typical Snakemake output file, which shows the error message as well as the command that caused it.
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 28
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       level_sample_compare_stat
        1
Select jobs to execute...

[Tue Dec  1 18:50:07 2020]
rule level_sample_compare_stat:
    input: fto_basedirs_unzipped/F4_fast5
    output: lsc_results/F4_ks_stat_fish0.tombo.stats
    log: logs/level_sample_compare_stat/F4_ks_stat_fish0.log
    jobid: 0
    wildcards: segment=4, test=ks, fisher=0
    threads: 28

tombo detect_modifications level_sample_compare --fast5-basedirs fto_basedirs_unzipped/F4_fast5 --alternate-fast5-basedirs /fs/project/PAS1405/GabbyLee/project/m6A_modif/ctrl_data_set/data_Olivier/f1f2_GL --statistics-file-basename lsc_results/F4_ks_stat_fish0 --fishers-method-context 0 --minimum-test-reads 0 --statistic-type ks --processes 28
Activating conda environment: /users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db
[18:51:03] Parsing Tombo index file(s).
******************** WARNING ********************
        Tombo index file does not exist for one or more directories.
                If --skip-index was not set for re-squiggle command, ensure that the specified directory is the same as for the re-squiggle command.
[19:39:31] Performing two-sample group comparison significance testing.
[19:39:31] Parsing Tombo index file(s).
[19:39:33] Calculating read coverage regions.
[19:39:33] Calculating read coverage.
[19:39:33] Calculating read coverage.
[19:39:33] Performing modified base detection across genomic regions.
  0%|          | 0/1 [00:00<?, ?it/s]Process Process-1:
Traceback (most recent call last):
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4359, in compute_group_reg_stats
    stat_type == KS_STAT_TEST_TXT)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4263, in compute_ks_tests
    samp_base_levels, ctrl_base_levels))])
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4262, in <listcomp>
    for i, (pos_samp_levels, pos_ctrl_levels) in enumerate(zip(
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4249, in compute_pos_ks_test
    d = np.max(np.absolute(samp_cdf - ctrl_cdf))
  File "<__array_function__ internals>", line 6, in amax
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

[Tue Dec  1 21:13:55 2020]
Finished job 0.
1 of 1 steps (100%) done
```

I couldn't find any irregularities with the data I fed to Tombo, though I should mention that the alternate fast5 base-directory is truly massive - it contains over 100,000 fast5 files. The other fast5 base-directory has 20,000 files. The alternate fast5 base-directory has a Tombo index, but the smaller directory does not.

I have used model_sample_compare quite a bit, but I have never run Tombo level_sample_compare before. Googling ``Tombo "ValueError: zero-size array to reduction operation maximum which has no identity"`` yields nothing.

This is my plan:
1. Reproduce the error outside Snakemake on a single Tombo run.
2. Try smaller ``--multiprocess-region-size`` arguments.
3. Downsample the alternate fast5 base-directory and try again.
4. If none of the above works, run Tombo with the pdb debugger and try to trace the error to its source.

Does anyone have any suggestions or know what's going wrong?

---

Updates:
1. After the error, Tombo does write .tombo.stats files like it should. However, these output files seem to not contain any data. Each .tombo.stats file is exactly 96 bytes. :(
2. Here is my Conda environment, in case it's useful. (It's just the minimum necessary to support ont-tombo.)
```
name: /users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.35.1=h17ad2fc_0
  - binutils_linux-64=2.35=hc3fd857_29
  - bwidget=1.9.14=ha770c72_0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2020.11.8=ha878542_0
  - cached-property=1.5.1=py_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2020.11.8=py36h5fab9bb_0
  - curl=7.71.1=he644dc0_8
  - fontconfig=2.13.1=h7e3eb15_1002
  - freetype=2.10.4=h7ca028e_0
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.2=py36h5fab9bb_2
  - gcc_impl_linux-64=9.3.0=h28f5a38_17
  - gcc_linux-64=9.3.0=h7247604_29
  - gettext=0.19.8.1=hf34092f_1004
  - gfortran_impl_linux-64=9.3.0=h2bb4189_17
  - gfortran_linux-64=9.3.0=ha1c937c_29
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=hf94e986_0
  - gxx_impl_linux-64=9.3.0=h53cdd4c_17
  - gxx_linux-64=9.3.0=h0d07fa4_29
  - h5py=3.1.0=nompi_py36hc1bc4f5_100
  - harfbuzz=2.7.2=ha5b49bf_1
  - hdf5=1.10.6=nompi_h1022a3e_1110
  - icu=67.1=he1b5a44_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hed1e6ac_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-devel_linux-64=9.3.0=hfd08b2a_17
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.3=hbe7bbb4_0
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=3_openblas
  - libnghttp2=1.41.0=hab1572f_1
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=9.3.0=h4084dd6_17
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - make=4.3=hd18ef5c_1
  - mappy=2.17=py36h955c1b8_2
  - markupsafe=1.1.1=py36he6145b8_2
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.4=py36h8732dcd_1
  - ont-tombo=1.5.1=py36r36h39af1c6_2
  - openssl=1.1.1h=h516909a_0
  - pango=1.42.4=h69149e4_5
  - pcre=8.44=he1b5a44_0
  - pip=20.2.4=py_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyfaidx=0.5.9.1=pyh864c0ab_1
  - python=3.6.11=h4d41432_2_cpython
  - python_abi=3.6=1_cp36m
  - pytz=2020.4=pyhd8ed1ab_0
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.2.0=r36h9e2df91_0
  - r-base=3.6.3=hc603457_4
  - r-bit=4.0.4=r36hcdcec82_0
  - r-bit64=4.0.5=r36hcdcec82_0
  - r-blob=1.2.1=r36h6115d3f_1
  - r-callr=3.5.1=r36h142f84f_0
  - r-cli=2.2.0=r36hc72bb7e_0
  - r-colorspace=2.0_0=r36h9e2df91_0
  - r-crayon=1.3.4=r36h6115d3f_1003
  - r-dbi=1.1.0=r36h6115d3f_1
  - r-dbplyr=2.0.0=r36hc72bb7e_0
  - r-desc=1.2.0=r36h6115d3f_1003
  - r-digest=0.6.27=r36h1b71b39_0
  - r-dplyr=1.0.2=r36h0357c0b_0
  - r-ellipsis=0.3.1=r36hcdcec82_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.1=r36hcdcec82_1
  - r-farver=2.0.3=r36h0357c0b_1
  - r-generics=0.1.0=r36hc72bb7e_0
  - r-ggplot2=3.3.2=r36hc72bb7e_1
  - r-glue=1.4.2=r36hcdcec82_0
  - r-gridextra=2.3=r36h6115d3f_1003
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-isoband=0.2.2=r36h0357c0b_0
  - r-labeling=0.4.2=r36h142f84f_0
  - r-lattice=0.20_41=r36hcdcec82_2
  - r-lifecycle=0.2.0=r36h6115d3f_1
  - r-magrittr=2.0.1=r36h9e2df91_1
  - r-mass=7.3_53=r36hcdcec82_0
  - r-matrix=1.2_18=r36h7fa42b6_3
  - r-memoise=1.1.0=r36h6115d3f_1004
  - r-mgcv=1.8_33=r36h7fa42b6_0
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-nlme=3.1_150=r36h580db52_0
  - r-pillar=1.4.7=r36hc72bb7e_0
  - r-pkgbuild=1.1.0=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.1.0=r36h0357c0b_0
  - r-plogr=0.2.0=r36h6115d3f_1003
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-prettyunits=1.1.1=r36h6115d3f_1
  - r-processx=3.4.4=r36hcdcec82_0
  - r-ps=1.4.0=r36h0eb13af_0
  - r-purrr=0.3.4=r36hcdcec82_1
  - r-r6=2.5.0=r36hc72bb7e_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
  - r-rcpp=1.0.5=r36he524a50_0
  - r-rlang=0.4.8=r36h9e2df91_0
  - r-rprojroot=2.0.2=r36hc72bb7e_0
  - r-rsqlite=2.2.1=r36h1b71b39_0
  - r-rstudioapi=0.13=r36hc72bb7e_0
  - r-scales=1.1.1=r36h6115d3f_0
  - r-testthat=2.3.2=r36h0357c0b_1
  - r-tibble=3.0.4=r36h0eb13af_0
  - r-tidyselect=1.1.0=r36h6115d3f_0
  - r-utf8=1.1.4=r36hcdcec82_1003
  - r-vctrs=0.3.5=r36h9e2df91_0
  - r-viridislite=0.3.0=r36h6115d3f_1003
  - r-withr=2.3.0=r36h6115d3f_0
  - r-zeallot=0.1.0=r36h6115d3f_1002
  - readline=8.0=he28a2e2_2
  - rpy2=2.9.4=py36r36hd767a1f_3
  - scipy=1.5.3=py36h9e8f40b_0
  - sed=4.8=he412f7d_0
  - setuptools=49.6.0=py36h9880bd3_2
  - simplegeneric=0.8.1=py_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_1
  - sysroot_linux-64=2.12=h77966d4_13
  - tk=8.6.10=hed695b0_1
  - tktable=2.10=hb7b940f_3
  - tqdm=4.7.2=py36_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
prefix: /users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db
```

**Comment by Chris-Kimmel** [comment]
I did the same thing I did earlier (with Snakemake and all) but I added ``--mutliprocess-region-size 100`` to the Tombo command. Some of the regions appear to have computed fine. One region threw the same error as before:
> ``ValueError: zero-size array to reduction operation maximum which has no identity``

Another region threw a brand new error:
> ``FloatingPointError: invalid value encountered in true_divide``.

The resulting .tombo.stats file is about 500kb .

Here is the full log file for one of the Tombo runs in my pipeline:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 28
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       level_sample_compare_pval
        1
Select jobs to execute...

[Wed Dec  2 16:22:09 2020]
rule level_sample_compare_pval:
    input: fto_basedirs_unzipped/F7_fast5
    output: lsc_results/F7_ks_pval_fish0.tombo.stats
    log: logs/level_sample_compare_pval/F7_ks_pval_fish0.log
    jobid: 0
    wildcards: segment=7, test=ks, fisher=0
    threads: 28

tombo detect_modifications level_sample_compare --fast5-basedirs fto_basedirs_unzipped/F7_fast5 --alternate-fast5-basedirs /fs/project/PAS1405/GabbyLee/project/m6A_modif/ctrl_data_set/data_Olivier/f1f2_GL --statistics-file-basename lsc_results/F7_ks_pval_fish0 --fishers-method-context 0 --minimum-test-reads 0 --statistic-type ks --store-p-value --multiprocess-region-size 100 --processes 28
Activating conda environment: /users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db
[16:23:48] Parsing Tombo index file(s).
******************** WARNING ********************
        Tombo index file does not exist for one or more directories.
                If --skip-index was not set for re-squiggle command, ensure that the specified directory is the same as for the re-squiggle command.
[17:13:13] Performing two-sample group comparison significance testing.
[17:13:13] Parsing Tombo index file(s).
[17:13:15] Calculating read coverage regions.
[17:13:15] Calculating read coverage.
[17:13:15] Calculating read coverage.
[17:13:15] Performing modified base detection across genomic regions.
 38%|███▊      | 35/92 [29:37<48:15, 50.79s/it]Process Process-5:
Traceback (most recent call last):
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4359, in compute_group_reg_stats
    stat_type == KS_STAT_TEST_TXT)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4263, in compute_ks_tests
    samp_base_levels, ctrl_base_levels))])
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4262, in <listcomp>
    for i, (pos_samp_levels, pos_ctrl_levels) in enumerate(zip(
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4246, in compute_pos_ks_test
    pos_samp_levels, pos_all_levels, side='right') / samp_n
FloatingPointError: invalid value encountered in true_divide
 84%|████████▎ | 77/92 [3:26:12<40:10, 160.68s/it]Process Process-1:
Traceback (most recent call last):
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4359, in compute_group_reg_stats
    stat_type == KS_STAT_TEST_TXT)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4263, in compute_ks_tests
    samp_base_levels, ctrl_base_levels))])
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4262, in <listcomp>
    for i, (pos_samp_levels, pos_ctrl_levels) in enumerate(zip(
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4249, in compute_pos_ks_test
    d = np.max(np.absolute(samp_cdf - ctrl_cdf))
  File "<__array_function__ internals>", line 6, in amax
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/users/PAS1405/kimmel/2020-11/find_edge_effect/.snakemake/conda/f23309db/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
 98%|█████████▊| 90/92 [4:03:51<05:25, 162.57s/it]
[Wed Dec  2 21:17:11 2020]
Finished job 0.
1 of 1 steps (100%) done
```

It looks like the error ``ValueError: zero-size array to reduction operation maximum which has no identity`` comes from C source code that Numpy uses. The text ``FloatingPointError: invalid value encountered in true_divide`` seems to come from the numpy source file ``numpy/lib/tests/test_arraypad.py``.

**Comment by Chris-Kimmel** [comment]
I think I found the problem. I used ``--minimum-test-reads 0`` instead of ``--minimum-test-reads 1``, so Tombo tried to compute a KS test at positions with zero coverage depth. I will reopen the issue if this doesn't fix it.

**Comment by marcus1487** [comment]
I had started to look into the error and thought this might be the case, but did not have time to confirm. I'm glad you were able to identify the issue.
