### ISSUE TITLE
tombo preprocess annotate_raw_with_fastqs have error?

### ISSUE THREAD

**Issue by xug15** [nanoporetech/tombo#315]
tombo preprocess annotate_raw_with_fastqs --fast5-basedir rawdata/ --fastq-filenames output/b2-merge/meth.fq.gz --overwrite
[15:54:00] Preparing reads and extracting read identifiers.
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 276.40it/s]
[15:54:00] Annotating FAST5s with sequence from FASTQs.
Process Process-4:
Traceback (most recent call last):
  File "/home/xugang/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xugang/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/app/tombo/tombo/_preprocess.py", line 148, in _feed_seq_records_worker
    fastq_rec = list(islice(fastq_fp, 4))
  File "/home/xugang/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by marcus1487** [comment]
This command does not accept gzipped input sequences. If you unzip the fastq file and retry the command it should work.
