### ISSUE TITLE
write_wiggles FileNotFoundError

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#32]
Hi,

This error just popped up -- I was not running into trouble with previous versions, so I am not sure what changed. I don't think I'm using the wrong syntax -- let me know if I am. 

Command =
```
tombo write_wiggles --wiggle-basename ${OUTDIR}/tombo --fast5-basedirs ${TEST} --control-fast5-basedirs ${CONT} --statistics-filename ${STATS} --wiggle-types coverage fraction signal signal_sd dwell difference
```

Error = 
```
Traceback (most recent call last):
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/bin/tombo", line 6, in <module>
    sys.exit(tombo.__main__.main())
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/__main__.py", line 175, in main
    text_output_commands.wiggle_main(args)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/text_output_commands.py", line 283, in wiggle_main
    args.wiggle_types, args.coverage_dampen_counts)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/text_output_commands.py", line 177, in write_all_wiggles
    write_cov_wig(raw_read_coverage2, wig_base, GROUP2_NAME)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/text_output_commands.py", line 154, in write_cov_wig
    _write_wiggle(wig_base, group_text, read_coverage, 'coverage', True)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/text_output_commands.py", line 34, in _write_wiggle
    wig_base + '.' + type_name + group_w_dot + '.plus.wig', 'wt')
FileNotFoundError: [Errno 2] No such file or directory: pairwise/compare/tombo.coverage.control.plus.wig'
```

**Comment by marcus1487** [comment]
My first guess would be that the `pairwise` or `compare` directories` do not exist. Tombo will not create these directories, so that would be the simplest explanation.

**Comment by JohnUrban** [comment]
Unfortunately, parsimony fails here and the directories do exist. In fact, other commands are working just fine with them -- see #34 .

**Comment by marcus1487** [comment]
I have tried to do a bit more digging here and I don't see any other obvious explanations for this error. Is it possible this command was mistakenly run for the wrong directory?

**Comment by JohnUrban** [comment]
Alright - for some reason it is just working today. Not sure what changed - but I will close this issue. Thanks for taking the time to look into it.
