### ISSUE TITLE
too many unexpected error when doing resquiggle

### ISSUE THREAD

**Issue by btrspg** [nanoporetech/tombo#327]
Hi there,

I have encounted an issue that to many error when I did the resquiggle sub command.

Here is the error log:
```
BaseCalled_template:::0037121d-bca5-444c-bb19-e1d91ffabebb.fast5
:::
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tombo/resquiggle.py", line 1570, in _resquiggle_worker
    map_res = adjust_map_res(map_res)
  File "/usr/local/lib/python3.8/dist-packages/tombo/resquiggle.py", line 1522, in adjust_map_res
    stall_ints=ts.identify_stalls(
  File "/usr/local/lib/python3.8/dist-packages/tombo/tombo_stats.py", line 313, in identify_stalls
    stall_metric[:] = np.NAN
ValueError: cannot convert float NaN to integer

```

And here is my command:
```
/usr/local/bin/tombo resquiggle --processes 20    \
    --num-most-common-errors 5    \
    --rna     \
    --basecall-group Basecall_1D_001    \
    --overwrite     \
    --ignore-read-locks  \
    single_fasta5_dir/ \
    transcriptome.fasta
```

And also my python version and package version: (`Python 3.8.5`)
```
Package             Version
------------------- --------------------
numpy               1.20.2
ont-fast5-api       3.3.0
ont-tombo           1.5.1
...
```

Hope to get your help.

Thanks in advance.

**Comment by btrspg** [comment]
I have tried down-graded the numpy to `1.19.0`. Tombo works again, and this issue may be caused by numpy>=1.20.0.

Hope anyone else meet this issue know how to fix it.

**Comment by marcus1487** [comment]
I believe the downgrade is probably the best solution. I'll try to push this numpy version pin into a new version.

**Comment by marcus1487** [comment]
This change has been made in github master.
