### ISSUE TITLE
Reads do not to contain basecalls

### ISSUE THREAD

**Issue by manburst** [nanoporetech/tombo#337]
Hello
I want to try tombo with my data by using quick start guide from your tutorial
by this command
`tombo resquiggle tex1/tex/allpasscall/workspace/test ref/ecoliref_genome.fasta --processes 4 --num-most-common-errors 5`
and error is occurred
```
`******************** ERROR ********************
        Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use `tombo preprocess annotate_raw_with_fastqs` to add basecalls from FASTQ files to raw FAST5 files.`
```
But this FAST5 file is output from `guppy_basecaller` with option `fast5_out`
I have tried
`tombo resquiggle tex1/tex/allpasscall/workspace/test ref/ecoliref_genome.fasta --processes 4 --num-most-common-errors 5 --basecall-group Basecall_1D_001`
but it still not working
Here screenshot from my FAST5 file
![image](https://user-images.githubusercontent.com/68594551/119232135-38d10e00-bb4e-11eb-873a-1fe626c59e43.png)

and for this command
`tombo detect_modifications alternative_model --fast5-basedirs path/to/fast5s/ \
    --statistics-file-basename native.e_coli_sample \
    --alternate-bases dam dcm --processes 4`
what is the `native.e_coli_sample` ?
Thanks in advance.

**Comment by manburst** [comment]
Ok I have tried new solution by convert my multi FAST5 file into single then rebasecall it.
Then performed preprocess with this command
`tombo preprocess annotate_raw_with_fastqs --fast5-basedir tex1/tex/passed/set1/test1/test2/single_out/workspace --fastq-filenames tex1/tex/passed/set1/test1/test2/single_out/fastq_runid_da42053ae2bd91f44d767ad5f6bc8c4d9fd2b04c_0_0.fastq --sequencing-summary-filenames tex1/tex/passed/set1/test1/test2/single_out/sequencing_summary.txt --overwrite`
Here is an output, I think it correctly adding the sequence to FASTQ file but which group of basecall they add?
`[11:43:59] Getting read filenames. [11:43:59] Parsing sequencing summary files. [11:43:59] Annotating FAST5s with sequence from FASTQs. 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.41it/s] [11:43:59] Added sequences to a total of 1 reads.`
Here the screenshot after preprocess
![image](https://user-images.githubusercontent.com/68594551/119248766-9badbe00-bbbd-11eb-8cbb-39ba9a125f96.png)
Then I performed resquiggle with this command
Here is an output with error
`[11:56:38] Loading minimap2 reference.
[11:56:38] Getting file list.
[11:56:38] Loading default canonical ***** RNA ***** model.
[11:56:38] Re-squiggling reads (raw signal to genomic sequence alignment).
5 most common unsuccessful read types (approx. %):
     -----
     -----
     -----
     -----
     -----
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.97it/s]
******************** WARNING ********************
        Unexpected errors occured. See full error stack traces for first (up to) 50 errors in "unexpected_tombo_errors.3541.err"
[11:56:39] Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 1 total reads):
   100.0% (      1 reads) : Unexpected error
[11:56:39] Saving Tombo reads index to file.
`
Error massage from file
`BaseCalled_template:::tex1/tex/passed/set1/test1/test2/single_out/workspace/00b8d316-c2ff-4695-a682-8a349421fc36.fast5
:::
Traceback (most recent call last):
  File "/home/kjirachote/miniconda3/lib/python3.8/site-packages/tombo/resquiggle.py", line 1570, in _resquiggle_worker
    map_res = adjust_map_res(map_res)
  File "/home/kjirachote/miniconda3/lib/python3.8/site-packages/tombo/resquiggle.py", line 1522, in adjust_map_res
    stall_ints=ts.identify_stalls(
  File "/home/kjirachote/miniconda3/lib/python3.8/site-packages/tombo/tombo_stats.py", line 313, in identify_stalls
    stall_metric[:] = np.NAN
ValueError: cannot convert float NaN to integer
`
and the screenshot after resquiggle
![image](https://user-images.githubusercontent.com/68594551/119248875-49b96800-bbbe-11eb-9564-37ecf59bd1ed.png)
The raw genome corrected has been added.
Is this successful or not?
Thanks in advance
