### ISSUE TITLE
plot_per_read -- TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#34]
Similar to #32 -- this error has now arisen with the newer version.

Note that many other commands work just fine, including:
```
resquiggle
test_significance
plot_genome_location
plot_most_significant
cluster_most_significant 
plot_max_difference
plot_motif_centered
plot_motif_with_stats
```

Command = 
```
tombo plot_per_read --per-read-statistics-filename ${PERSTATS} --genome-locations D:1000 --num-bases 42 --fast5-basedirs ${TEST} 
```

Output = 
```
Parsing genome locations.
Parsing tombo index file(s).
Parsing per read statistics.

Traceback (most recent call last):
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/bin/tombo", line 6, in <module>
    sys.exit(tombo.__main__.main())
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/__main__.py", line 180, in main
    plot_commands.plot_main(args)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/plot_commands.py", line 2157, in plot_main
    plot_per_read_mods_genome_location(*base_args, **kwargs)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/plot_commands.py", line 1511, in plot_per_read_mods_genome_location
    int_stats = per_read_stats.get_region_stats(int_data, num_reads)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/tombo_stats.py", line 1287, in get_region_stats
    all_int_stats['read_id'] in int_plot_reads]
TypeError: unhashable type: 'numpy.ndarray'
```

Maybe ```all_int_stats['read_id'] in list(int_plot_reads)``` will help?

**Comment by JohnUrban** [comment]
Actually it seems like it might be ```all_int_stats``` since I now see you define int_plot_reads as a set a line or 2 above it.

**Comment by JohnUrban** [comment]
Then again it seems to successfully pull off ```all_int_stats['read_id']``` a few lines above that....

**Comment by marcus1487** [comment]
This actually had to do with the fact that `all_int_stats['read_id']` is a numpy array itself and the default for `in` is not to perform element-wise set membership, but instead testing for membership of the whole `ndarray` (and this was somehow missed by my tests as well; fixing this now). This has been fixed in the minor bug fix just pushed.

**Comment by JohnUrban** [comment]
Thanks for looking into it!

**Comment by JohnUrban** [comment]
I am guessing that I need to ```git clone``` or ```pull``` the minor bug fix rather than ```conda install -c bioconda ont-tombo``` or ```conda update``` -- correct?

**Comment by marcus1487** [comment]
Yes, I'm treating this as a minor bug fix, so yes it will not be added to pip or conda until the next release.

**Comment by JohnUrban** [comment]
I'm now getting this error centered on the same line/area:
```
Traceback (most recent call last):
  File "/users/jurban/data/software/conda/tombo/tombo/git/tombo/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.2', 'console_scripts', 'tombo')()
  File "/users/jurban/data/software/conda/tombo/tombo/git/tombo/lib/python3.6/site-packages/ont_tombo-1.2-py3.6-linux-x86_64.egg/tombo/__main__.py", line 179, in main
    from . import plot_commands
  File "/users/jurban/data/software/conda/tombo/tombo/git/tombo/lib/python3.6/site-packages/ont_tombo-1.2-py3.6-linux-x86_64.egg/tombo/plot_commands.py", line 26, in <module>
    from . import tombo_stats as ts
  File "/users/jurban/data/software/conda/tombo/tombo/git/tombo/lib/python3.6/site-packages/ont_tombo-1.2-py3.6-linux-x86_64.egg/tombo/tombo_stats.py", line 1288
    for read_id in all_int_stats['read_id']]
      ^
SyntaxError: invalid syntax
```

I get that for test_significance, write_wiggle, and other sub-commands too now.

**Comment by JohnUrban** [comment]
Code in tombo_stats.py lines 1279-1288 (https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_stats.py):
```
        all_int_stats = int_block_stats[
            (int_block_stats['pos'] >= interval_data.start) &
            (int_block_stats['pos'] < interval_data.end)]

        read_ids = set(all_int_stats['read_id'])
        if num_reads is not None and num_reads < len(read_ids):
            int_plot_reads = set(random.sample(read_ids, num_reads))
            all_int_stats = all_int_stats[
                read_id in int_plot_reads
                for read_id in all_int_stats['read_id']] ## offending line is here
```

I can reproduce this error as:
```
>>> int_plot_reads = set(['a','b','c','d'])
>>> all_int_stats = np.array(['b','c'])
>>> all_int_stats[read_id in int_plot_reads for read_id in all_int_stats]
SyntaxError: invalid syntax

## w/o indexing it creates boolean list
>>> [read_id in int_plot_reads for read_id in all_int_stats]
[True, True]
type([read_id in int_plot_reads for read_id in all_int_stats])
<type 'list'>

## can fix (maybe get your desired result) with:
>>> all_int_stats[np.array([read_id in int_plot_reads for read_id in all_int_stats])]
array(['b', 'c'], 
      dtype='|S1')

```

**Comment by JohnUrban** [comment]
Well I can definitely say that making this change allows tombo to run again (i.e. not throw the SyntaxError and quit):
```
        read_ids = set(all_int_stats['read_id'])
        if num_reads is not None and num_reads < len(read_ids):
            int_plot_reads = set(random.sample(read_ids, num_reads))
            all_int_stats = all_int_stats[np.array([read_id in int_plot_reads for read_id in all_int_stats['read_id']])]
```

It is currently running ```test_significance```.

I will have to leave it to you to say whether that change is actually doing what you intended.

**Comment by JohnUrban** [comment]
I can confirm that your latest commit is working. Many thanks. I will now hopefully disappear for a while. :)

**Comment by marcus1487** [comment]
Great. Not sure how my test missed this again, but I am glad this is sorted out now. Best luck mod-hunting!
