### ISSUE TITLE
tombo preprocess error

### ISSUE THREAD

**Issue by wentski** [nanoporetech/tombo#383]
Hello,

I am having trouble running `tombo preprocess` on my samples. I have tried running the command both for samples which were basecalled during the sequencing run on MinKnow and for samples which were basecalled post-sequencing using guppy. Both methods give the same error. I have even tried removing basecalling tags using ont-fast5-api's --sanitize option and rebasecalling but get the same result:

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/sxtm38/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/sxtm38/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sxtm38/miniconda3/lib/python3.7/site-packages/tombo/resquiggle.py", line 1667, in _io_and_mappy_thread_worker
    sig_len_rng, seq_len_rng)
  File "/home/sxtm38/miniconda3/lib/python3.7/site-packages/tombo/resquiggle.py", line 1395, in _io_and_map_read
    all_raw_signal = th.get_raw_read_slot(fast5_data)['Signal'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/sxtm38/miniconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 366, in h5py._selector.Reader.read
OSError: Can't read data (can't open directory: /home/sxtm38/miniconda3/lib/hdf5/plugin)

Strangely, running the same command on older files works fine. Is there perhaps an incompatibility with certain guppy versions? I am really not sure what to make of this. Any help appreciated.

**Comment by AnWiercze** [comment]
Same issue!

**Comment by AnWiercze** [comment]
In my case, the HDF5_PLUGIN_PATH is already exported and stored in the bashrc.

**Comment by AnWiercze** [comment]
Could solve the issue by installing the ont-vbz plugin via anaconda and python 3.6:
 conda install -c bioconda ont_vbz_hdf_plugin

**Comment by wentski** [comment]
Issue solved. I downloaded the ont-vbz plugin and placed a copy in the miniconda3/lib/hdf5/plugin folder. Thanks for the suggestions.
