### ISSUE TITLE
Type of output from `text_output browser_files` with input from `level_sample_compare`

### ISSUE THREAD

**Issue by dariober** [nanoporetech/tombo#385]
Hi- I would like to check which  types of output are available to the subcommand **`tombo text_output browser_files`** when the input comes from **`tombo detect_modifications level_sample_compare`**. 

I produced sample statistics without errors with: 

```
tombo detect_modifications level_sample_compare \
    --fast5-basedirs {input.fast5_dir} \
    --statistics-file-basename ${base} \
    --alternate-fast5-basedirs {input.ctrl_dir} \
    --statistic-type t \
    --minimum-test-reads 30 \
    --processes 16
```

When I try to produce text output for valid_coverage, fraction, dampen_fraction I get (for e.g. type valid_coverage):

```
tombo text_output browser_files \
    --fast5-basedirs fast5/01_BS \
    --statistics-filename tombo/level_sample_compare/01_BS.tombo.stats \
    --browser-file-basename tombo/level_sample_compare/browser_files/01_BS \
    --file-types valid_coverage

[12:08:16] Parsing Tombo index file(s).
[12:08:19] Loading statistics from file.
[12:08:21] Parsing and outputting statistics wiggles.
Traceback (most recent call last):
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/__main__.py", line 269, in main
    _text_output_commands._browser_files_main(args)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 458, in _browser_files_main
    args.motif_descriptions)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 383, in write_all_browser_files
    VCOV_WIG_TYPE in wig_types, motif_descs, fasta_fn)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 207, in write_frac_wigs
    if do_vcov: curr_vcov.append(block_stats[VCOV_SLOT])
ValueError: no field of name valid_cov
```

Or, for type fraction:

```
tombo text_output browser_files \
    --fast5-basedirs fast5/01_BS \
    --statistics-filename tombo/level_sample_compare/01_BS.tombo.stats \
    --browser-file-basename tombo/level_sample_compare/browser_files/01_BS \
    --file-types fraction

[12:09:07] Parsing Tombo index file(s).
[12:09:11] Loading statistics from file.
[12:09:12] Parsing and outputting statistics wiggles.
Traceback (most recent call last):
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/__main__.py", line 269, in main
    _text_output_commands._browser_files_main(args)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 458, in _browser_files_main
    args.motif_descriptions)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 383, in write_all_browser_files
    VCOV_WIG_TYPE in wig_types, motif_descs, fasta_fn)
  File "/export/projects/III-data/wcmp_bioinformatics/db291g/miniconda3/envs/20211218_marija/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 204, in write_frac_wigs
    if do_frac: curr_fracs.append(1 - block_stats[FRAC_SLOT])
ValueError: no field of name frac
```

Type coverage and statistic work fine.

Is this expected or is there something wrong?

**Comment by marcus1487** [comment]
This is the expected behavior. The `level_sample_compare` method compares a group of signals versus another group of signals to produce a single metric per-reference position. Other methods produce per-read metrics, to which a hard threshold is then applied. These hard thresholding metrics result in a `frac` tion of reads identified as modified and a `valid_cov` erage for the total reads that passed the hard threshold. 

See more details on the stats available here: https://nanoporetech.github.io/tombo/modified_base_detection.html#tombo-statistics-file-format
