### ISSUE TITLE
A question about the text-ouput

### ISSUE THREAD

**Issue by Tomcxf** [nanoporetech/tombo#387]
Hi！Dear developer,
Thanks for your work and share.
Recently I met a question after detect modification.
I got the stat file and wanna to generate the output file.But when I type：

tombo text_output browser_files --fast5-basedirs ../single_merge/ --statistics-filename tombo.RNA.5mC.model.5mC.tombo.stats --file-types coverage dampened_fraction --browser-file-basename soybean_out
[13:13:57] Parsing Tombo index file(s).
[13:14:13] Getting and writing  coverage bedgraphs.
[13:14:13] Calculating read coverage regions.
[13:14:13] Calculating read coverage.
[13:14:22] Loading statistics from file.
Traceback (most recent call last):
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/tombo_stats.py", line 2680, in __init__
    self._parse_stats()
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/tombo_stats.py", line 2566, in _parse_stats
    self._fp = h5py.File(self.stats_fn, 'r')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (addr overflow, addr = 6144, size = 88, eoa = 2048)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/tombo_stats.py", line 3233, in TomboStats
    stats = ModelStats(stat_fn)
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/tombo_stats.py", line 2685, in __init__
    'was created before Tombo v1.3.1')
tombo.tombo_helper.TomboError: Invalid statistics file provided. Try running tombo/scripts/convert_stats.py if this stats file was created before Tombo v1.3.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tombo", line 33, in <module>
    sys.exit(load_entry_point('ont-tombo', 'console_scripts', 'tombo')())
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/__main__.py", line 269, in main
    _text_output_commands._browser_files_main(args)
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/_text_output_commands.py", line 461, in _browser_files_main
    args.motif_descriptions)
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/_text_output_commands.py", line 372, in write_all_browser_files
    all_stats = ts.TomboStats(stats_fn)
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/tombo_stats.py", line 3235, in TomboStats
    stats = LevelStats(stat_fn)
  File "/home/ubuntu/xf/cxf/keiwen/soybean0116/tombo/tombo/tombo/tombo_stats.py", line 3146, in __init__
    'was created before Tombo v1.3.1')
tombo.tombo_helper.TomboError: Invalid statistics file provided. Try running tombo/scripts/convert_stats.py if this stats file was created before Tombo v1.3.1

I use different environment to anlaysis, and below tombo was installed by pip

When I use tombo installed by conda
I got the similar result

tombo text_output browser_files --fast5-basedirs ../single_merge/ --statistics-filename tombo.RNA.5mC.model.5mC.tombo.stats --file-types coverage dampened_fraction --browser-file-basename soybean0116_5mC
[13:30:53] Parsing Tombo index file(s).
[13:31:09] Getting and writing  coverage bedgraphs.
[13:31:09] Calculating read coverage regions.
[13:31:09] Calculating read coverage.
[13:31:18] Loading statistics from file.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/tombo_stats.py", line 2680, in __init__
    self._parse_stats()
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/tombo_stats.py", line 2566, in _parse_stats
    self._fp = h5py.File(self.stats_fn, 'r')
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/h5py/_hl/files.py", line 445, in __init__
    swmr=swmr)
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (addr overflow, addr = 6144, size = 88, eoa = 2048)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cxf/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/__main__.py", line 269, in main
    _text_output_commands._browser_files_main(args)
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 458, in _browser_files_main
    args.motif_descriptions)
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/_text_output_commands.py", line 372, in write_all_browser_files
    all_stats = ts.TomboStats(stats_fn)
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/tombo_stats.py", line 3235, in TomboStats
    stats = LevelStats(stat_fn)
  File "/home/ubuntu/anaconda3/envs/cxf/lib/python3.7/site-packages/tombo/tombo_stats.py", line 3145, in __init__
    'tombo/scripts/convert_stats.py if this stats file ' +
tombo.tombo_helper.TomboError: Invalid statistics file provided. Try running tombo/scripts/convert_stats.py if this stats file was created before Tombo v1.3.1

I try the previous document had been anlaysised by tombo well（the same pipline with the same version） with the same command.But its stats file works well and no error.
I am so confused and hope for help, thanks

**Comment by Tomcxf** [comment]
I have noticed something after several test.
I ran the same command on my early research. When i ran modification and output, it worked well. So it seemed that the .stat file has problem.
And when i test the questioned file, it showed that after the modification`s process reached 100%, i can not type any command ,seem as the command did not finish yet.
The test file is far smaller than the problem one.so i do not sure if the problem is too large so it will take more time to generate stat file ,but i stop it so it is broken
or it just a bug？

**Comment by siyuyang1013** [comment]
I get the same error, Do you know how to solve this error now?
