### ISSUE TITLE
Tombo resquiggle error

### ISSUE THREAD

**Issue by rowanhowellGE** [nanoporetech/tombo#405]
Hi,

I am trying to resquiggle some fast5s but am running into the following error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/tombo", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/tombo/__main__.py", line 230, in main
    from . import resquiggle
  File "/opt/conda/lib/python3.9/site-packages/tombo/resquiggle.py", line 44, in <module>
    from . import tombo_stats as ts
  File "/opt/conda/lib/python3.9/site-packages/tombo/tombo_stats.py", line 84, in <module>
    HALF_NORM_EXPECTED_VAL = stats.halfnorm.expect()
  File "/opt/conda/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2927, in expect
    dub = integrate.quad(fun, d, ub, **kwds)[0]
  File "/opt/conda/lib/python3.9/site-packages/scipy/integrate/_quadpack_py.py", line 411, in quad
    retval = _quad(func, a, b, args, full_output, epsabs, epsrel, limit,
  File "/opt/conda/lib/python3.9/site-packages/scipy/integrate/_quadpack_py.py", line 525, in _quad
    return _quadpack._qagie(func,bound,infbounds,args,full_output,epsabs,epsrel,limit)
  File "/opt/conda/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2904, in fun
    return x * self.pdf(x, *args, **lockwds)
  File "/opt/conda/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2094, in pdf
    place(output, cond, self._pdf(*goodargs) / scale)
  File "/opt/conda/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py", line 3820, in _pdf
    return np.sqrt(2.0/np.pi)*np.exp(-x*x/2.0)
FloatingPointError: underflow encountered in exp
```
Any ideas on how this can be resolved?

If it helps my data is multi-read, so I have first converted to single reads with ont-fast5-api. This means my fast5 folder contains several sub-folders containing the actual fast5 files. However, I get the same error running on the topmost folder (fast5s/) or subfolders (fast5s/0/).

Thanks

**Comment by rowanhowellGE** [comment]
I fixed this issue by using scipy version 1.7.3, rather than 1.9.0. Could this be added to dependencies?
