### ISSUE TITLE
Tombo resquiggle error

### ISSUE THREAD

**Issue by q1134269149** [nanoporetech/tombo#406]
Hi,
 After basecalling with guppy, I using tombo to resquiggle the fast5 files of nanopore direct RNA-seq data. However, I checked the log and got the result as follows:

 **_Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 1512917 total reads):
    89.2% (1349733 reads) : Unexpected error
    10.8% ( 163147 reads) : Alignment not produced
     0.0% (     37 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)_**

I next checked the "unexpected_tombo_errors.5558.err" file, and found the same error for all single fast5 file as follows:

**_BaseCalled_template:::/mouse/qinhang_backup/guppy324/Calu_2_Infected/workspace/366/58719684-9a20-46b3-bf1a-9d95fd6185b1.fast5
:::
Traceback (most recent call last):
  File "/home/qinhang1/anaconda3/envs/tombo/lib/python3.7/site-packages/tombo/resquiggle.py", line 1570, in _resquiggle_worker
    map_res = adjust_map_res(map_res)
  File "/home/qinhang1/anaconda3/envs/tombo/lib/python3.7/site-packages/tombo/resquiggle.py", line 1523, in adjust_map_res
    map_res.raw_signal, DEFAULT_STALL_PARAMS))
  File "/home/qinhang1/anaconda3/envs/tombo/lib/python3.7/site-packages/tombo/tombo_stats.py", line 313, in identify_stalls
    stall_metric[:] = np.NAN
ValueError: cannot convert float NaN to integer

BaseCalled_template:::/mouse/qinhang_backup/guppy324/Calu_2_Infected/workspace/366/67226511-134b-4016-847f-5a2a2326ff11.fast5
:::
Traceback (most recent call last):
  File "/home/qinhang1/anaconda3/envs/tombo/lib/python3.7/site-packages/tombo/resquiggle.py", line 1570, in _resquiggle_worker
    map_res = adjust_map_res(map_res)
  File "/home/qinhang1/anaconda3/envs/tombo/lib/python3.7/site-packages/tombo/resquiggle.py", line 1523, in adjust_map_res
    map_res.raw_signal, DEFAULT_STALL_PARAMS))
  File "/home/qinhang1/anaconda3/envs/tombo/lib/python3.7/site-packages/tombo/tombo_stats.py", line 313, in identify_stalls
    stall_metric[:] = np.NAN
ValueError: cannot convert float NaN to integer_**

What's the problem, please? 
Thanks!
hqin

**Comment by q1134269149** [comment]
This the log file.
[unexpected_tombo_errors.5558.err.txt](https://github.com/nanoporetech/tombo/files/9300972/unexpected_tombo_errors.5558.err.txt)

**Comment by JBerthelier** [comment]
Hi sorry to come to the conversation, I have the same issue by trying to use your DENA tool.
Best,

**Comment by diegochavesm** [comment]
So after:

1. multi_to_single (Multi fast5 to single fast5)

i got the same behavior, most of my reads are ending up in the "Unexpected Error"

From the re-squiggling output
 55.7% (   3399 reads) : Unexpected error
 44.4% (   2708 reads) : Alignment not produced

all thought almost 3k reads were sorted in "Unexpected error" in the *.err  4 files aren't all of them, per file 50 reads (200 ca).

fast5 structure looks like:  

/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/BaseCalled_template/Move Dataset {4697}
/Analyses/Basecall_1D_000/BaseCalled_template/Trace Dataset {4697, 8}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/RawGenomeCorrected_000 Group
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_1684     Group


any idea, what could be?

**Comment by q1134269149** [comment]
> Hi sorry to come to the conversation, I have the same issue by trying to use your DENA tool. Best,

I created an environment of conda, and solved this problem by changing the version of python from 3.8 to 3.6, and the version of numpy from 1.23 to 1.19.

Best,
hqin

**Comment by hengjwj** [comment]
Thanks hqin! It worked for me once I downgraded to numpy<1.20:

numpy                     1.19.5           py37h3e96413_3    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
