### ISSUE TITLE
FloatingPointError: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by Bessyyi** [nanoporetech/tombo#435]
tombo plot roc --statistics-filenames nat_ccwgg.dcm.tombo.stats wga_ccwgg.dcm.tombo.stats --motif-descriptions CCWGG:2:"dcm 5mC Alt. Model" CCWGG:2:"wga 5mC Alt. Model"  --genome-fasta /home/ywj/ref/EC.fasta 
[21:13:15] Parsing motifs.
[21:13:15] Parsing genome.
[21:13:17] Computing accuracy statistics.
      Statistic Type                AUC       mean AP
      --------------                ---       -------
Traceback (most recent call last):
  File "/home/ywj/yzy/miniconda3/envs/ont-tom/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/home/ywj/yzy/miniconda3/envs/ont-tom/lib/python3.6/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/home/ywj/yzy/miniconda3/envs/ont-tom/lib/python3.6/site-packages/tombo/_plot_commands.py", line 2344, in plot_main
    plot_roc(**kwargs)
  File "/home/ywj/yzy/miniconda3/envs/ont-tom/lib/python3.6/site-packages/tombo/_plot_commands.py", line 147, in plot_roc
    all_stats)
  File "/home/ywj/yzy/miniconda3/envs/ont-tom/lib/python3.6/site-packages/tombo/_plot_commands.py", line 71, in prep_accuracy_rates
    ordered_mod_tf)
  File "/home/ywj/yzy/miniconda3/envs/ont-tom/lib/python3.6/site-packages/tombo/tombo_stats.py", line 2391, in compute_accuracy_rates
    fp_rate = fp_cumsum / fp_cumsum[-1]
FloatingPointError: invalid value encountered in true_divide
Can yougive me some suggestions,Thanks!

**Comment by marcus1487** [comment]
Tombo is deprecated. I would recommend transferring this analysis to Remora and/or modkit moving forward.
