### ISSUE TITLE
Fail to Install tombo using venv3 Ubuntu18.04

### ISSUE THREAD

**Issue by abadouh** [nanoporetech/tombo#452]
Hey, 
I am trying to install tombo using pip and or the git repository and I get the same error.
Below you can find the details:

OS: Ubuntu18.04
Python: 3.8
numpy: 1.24.4

**Using pip**
```
mkdir tombo 
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install numpy
pip install ont-tombo[full]
```

**Using github**
```
git clone https://github.com/nanoporetech/tombo 
cd tombo/
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install numpy
pip install -e .
```

I get the following error:

```
Obtaining file:///home/workspaces/benchmark/tombo/tombo
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      ************************************************************
      INSTALLATION ERROR:
          Need to install numpy before tombo installation.
          This is required in order to get maximum efficincy from cython code optimizations.
      To install run:
      $ pip install numpy
      ************************************************************
      /tmp/pip-build-env-9yil7j94/overlay/lib/python3.8/site-packages/setuptools/build_meta.py:487: SetuptoolsDeprecationWarning: Running `setup.py` directly as CLI tool is deprecated.
      !!
      
              ********************************************************************************
              Please avoid using `sys.exit(0)` or similar statements that don't fit in the paradigm of a configuration file.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        super().run_setup(setup_script=setup_script)
      Traceback (most recent call last):
        File "/home/workspaces/benchmark/tombo/tombo/venv3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/workspaces/benchmark/tombo/tombo/venv3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/workspaces/benchmark/tombo/tombo/venv3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-9yil7j94/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 453, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/tmp/pip-build-env-9yil7j94/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self._bubble_up_info_directory(metadata_directory, ".egg-info")
        File "/tmp/pip-build-env-9yil7j94/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 337, in _bubble_up_info_directory
          info_dir = self._find_info_directory(metadata_directory, suffix)
        File "/tmp/pip-build-env-9yil7j94/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 348, in _find_info_directory
          assert len(candidates) == 1, f"Multiple {suffix} directories found"
      AssertionError: Multiple .egg-info directories found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by marcus1487** [comment]
It appears as though pip is not finding the numpy install. This may be an issue with your python environment or the way Tombo runs setup. Tombo is deprecated and I would recommend moving to Remora for raw signal analysis.
