### ISSUE TITLE
All reads (un)successfully re-squiggled

### ISSUE THREAD

**Issue by gkr2381** [nanoporetech/tombo#53]
**Hi Marcus,**

**When I run my tombo re-squiggle, I get a few warnings and then it comes back with 'All reads successfully re-squiggled!':**

tombo resquiggle /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171016_2119_invitro\ m6A\ copy/fast5/pass/ /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171016_2119_invitro\ m6A\ copy/fastq/pass/ --minimap2-executable /Volumes/Macintosh\ HD/Users/PhielLabMinION/minimap2/ --processes 4

Getting file list.

Estimating global scale parameter

Correcting 1648 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).

Process Process-2:

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap self.run()

  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python2.7/site-packages/tombo/resquiggle.py", line 1552, in _alignment_worker genome_index = th.parse_fasta(genome_fn)

  File "/usr/local/lib/python2.7/site-packages/tombo/tombo_helper.py", line 754, in parse_fasta fasta_fp = open(fasta_fn)

IOError: [Errno 21] Is a directory: '/Volumes/Macintosh HD/Library/MinKNOW/data/reads/copy20171016_2119_invitro m6A copy/fastq/pass/'

All reads successfully re-squiggled!

**It also says this for my control read:**

tombo resquiggle /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171004_2138_invitro\ RNA\ copy/fast5/pass/ /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171004_2138_invitro\ RNA\ copy/fastq/pass/ --minimap2-executable /Volumes/Macintosh\ HD/Users/PhielLabMinION/minimap2/ --processes 4

Getting file list.

Estimating global scale parameter

Correcting 128329 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).

Process Process-2:

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap self.run()

  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python2.7/site-packages/tombo/resquiggle.py", line 1552, in _alignment_worker genome_index = th.parse_fasta(genome_fn)

  File "/usr/local/lib/python2.7/site-packages/tombo/tombo_helper.py", line 754, in parse_fasta fasta_fp = open(fasta_fn)

IOError: [Errno 21] Is a directory: '/Volumes/Macintosh HD/Library/MinKNOW/data/reads/copy20171004_2138_invitro RNA copy/fastq/pass/'

All reads successfully re-squiggled!

**The command comes back and says it will print a dot for each 500 reads completed (which I've seen it do before in setup commands) but I'm not seeing any of the dots I was anticipating. I'm wondering if the command is unable to re-squiggle any of the files, and if it's just skipping over the ones it can't read (all of them, maybe) and then saying it's complete. I tried to continue downstream and do the comparison method just to see what would happen, but with no luck:**

tombo test_significance --fast5-basedirs /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171016_2119_invitro\ m6A\ copy/fast5/pass/ --control-fast5-basedirs /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171004_2138_invitro\ RNA\ copy/fast5/pass/ --statistics-file-basename sample_cononical_compare

Parsing tombo index file(s).

Performing two-sample comparison significance testing.

Parsing tombo index file(s).

Performing significance testing across 0 regions. (Will print a dot for each batch completed)

********** ERROR *********

No genomic positions contain --minimum-test-reads.

**Am I making any obvious errors here?**

**Thanks, Gabrielle**

**Comment by marcus1487** [comment]
I think there are two issues with the command. The first is that each resquiggle call takes a singe base directory of fast5 files. You can fix this by either linking several directories into a single directory or making several separate resquiggle calls. The second positional argument to resquiggle should then be a reference fasta file. 

The other issue is that this appears to be from an older version of tombo as a minimap2 executable is no longer required.

**Comment by gkr2381** [comment]
Ah, well that would certainly do it. I'll redo this then tomorrow and hopefully I won't have any more issues.
Thank you!

**Comment by gkr2381** [comment]
**Hi again Marcus,**

**I upgraded tombo today just fine. However, I'm now getting a different error when I run my re-squiggle command:**

tombo resquiggle /Volumes/Macintosh\ HD/Library/MinKNOW/data/reads/copy20171016_2119_invitro\ m6A\ copy/fast5/pass/0/ /Volumes/Macintosh\ HD/Library/MinKNOW/mm\ DNA\ reference\ genome/mm10/Mus_musculus.GRCm38.dna.chromosome.10.fa  --processes 4

Loading minimap2 reference.

Getting file list.

Using default canonical ***** RNA ***** model.

Estimating global scale parameter

Traceback (most recent call last):

  File "/usr/local/bin/tombo", line 11, in <module> load_entry_point('ont-tombo==1.2.1', 'console_scripts', 'tombo')()

  File "/usr/local/lib/python2.7/site-packages/tombo/__main__.py", line 135, in main resquiggle.resquiggle_main(args)

  File "/usr/local/lib/python2.7/site-packages/tombo/resquiggle.py", line 1295, in resquiggle_main
args.segmentation_parameters, args.genome_fasta)

  File "/usr/local/lib/python2.7/site-packages/tombo/resquiggle.py", line 1132, in resquiggle_all_reads daemon=True)

TypeError: __init__() got an unexpected keyword argument 'daemon'


**The ...fast5/pass/0 is the only directory for this run. Is the issue with my reference genome .fa perhaps?**

**Comment by marcus1487** [comment]
How did you update tombo? This python2.7 specific bug was introduced in the 1.2.1 release and fixed very recently in the 1.2.1.2. The most recent version should have this issue resolved.

**Comment by gkr2381** [comment]
I updated it using 
`sudo pip install ont-tombo --upgrade`

**Comment by marcus1487** [comment]
I think I have resolved this issue. Give the update command a try one more time and you should be good to go.

In case you (or anyone) was interested the updated version had been uploaded to pypi, but I made a mistake in my package version numbering. I originally designated the most recent release (1.2.1.2) as release 1.2.1b, but both conda and apparently pypi recognize this as a beta release coming before 1.2.1. So even though the 1.2.1b release was pushed after 1.2.1 and that pypi was showing release 1.2.1b as the current release, the 1.2.1 release was still the default install release from pypi. Converting this release to version number 1.2.1.2 seems to have fix this issue. This is all probably way to much information for you, but thought it might be worth noting for anyone else that is interested.
