### ISSUE TITLE
write_most_significant_fasta error

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/tombo#57]
Hi Marcus,

I ran into the  error below while running  'tombo write_most_significant_fasta'.
Can you help me with it?
Thanks a lot.

$ tombo write_most_significant_fasta --statistics-filename WT_VS_KO_canonical_sample_CMP_stats.tombo.stats --genome-fasta ../reference_genome.fa --sequences-filename WT_VS_KO_canonical_sample_CMP_stats.tombo.stats.fasta

Loading statistics from file.
Traceback (most recent call last):
  File "/home/hualiu/h.liu/Bin/anaconda2/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.2.1b0', 'console_scripts', 'tombo')()
  File "build/bdist.linux-x86_64/egg/tombo/__main__.py", line 171, in main
  File "build/bdist.linux-x86_64/egg/tombo/text_output_commands.py", line 335, in write_signif_diff_main
  File "build/bdist.linux-x86_64/egg/tombo/text_output_commands.py", line 261, in write_most_signif
AttributeError: 'dict' object has no attribute 'index'

**Comment by marcus1487** [comment]
This is an issue with the optional dependency `pyfaidx`. If you install `pyfaidx` you should be able to get around this issue for now, but I will include a fix for this without installing `pyfaidx` shortly as well.

**Comment by marcus1487** [comment]
I have pushed a fix for this issue. I will include this in the next release, but for now this will only be available via a github repo installation.
