### ISSUE TITLE
Error when running plot commands

### ISSUE THREAD

**Issue by alexredon** [nanoporetech/tombo#78]
Hi !
I have a similar error than the issue #29  when I am trying to plot most significant regions : 

```
tombo plot most_significant --fast5-basedirs my_fastDir --statistics-filename test.tombo.stats

******************** ERROR ********************
	R and rpy2 must be linked during installation.
		Run python -c "from rpy2 import robjects; from rpy2.robjects.packages import importr to identify installation linking issues.
		If using conda, check that R and rpy2 are installed from the same channel with conda list | grep "r-base\|rpy2" (last columns should match).
```

When running:

```
python2.7 -c "import rpy2.robjects; from rpy2.robjects.packages import importr"
```

I get this : 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: dlopen(/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/_rinterface.so, 2): Library not loaded: @rpath/libintl.9.dylib
  Referenced from: /Users/black/anaconda3/envs/nanopore/lib/R/lib/libR.dylib
  Reason: image not found
```

and when running : 

```
python -m rpy2.tests
```

I get : 

```
Traceback (most recent call last):
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/tests.py", line 23, in <module>
    import rpy2.tests_rpy_classic
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/tests_rpy_classic.py", line 3, in <module>
    import rpy2.rpy_classic as rpy
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rpy_classic.py", line 5, in <module>
    import rpy2.rinterface as ri
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: dlopen(/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/_rinterface.so, 2): Library not loaded: @rpath/libintl.9.dylib
  Referenced from: /Users/black/anaconda3/envs/nanopore/lib/R/lib/libR.dylib
  Reason: image not found
```

conda list : 

```
packages in environment at /Users/black/anaconda3/envs/nanopore:

Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1  
basecRAWller              0.1                       <pip>
blas                      1.0                         mkl  
bwa                       0.7.15                        1    bioconda
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.8                        0  
certifi                   2018.4.16                py27_0  
curl                      7.60.0               ha441bb4_0  
cython                    0.28.3           py27h1de35cc_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
fribidi                   1.0.4                h1de35cc_0  
funcsigs                  1.0.2                     <pip>
future                    0.16.0                   py27_1  
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.50.2                        1  
graphite2                 1.3.11               h2098e52_2  
gsl                       2.4                  h1de35cc_4  
h5py                      2.7.0            py27h217cc45_1  
harfbuzz                  0.9.39                        2  
hdf5                      1.10.1               ha036c08_1  
icu                       54.1                          0  
intel-openmp              2018.0.3                      0  
jpeg                      9b                   he5867d9_2  
libcurl                   7.60.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libdeflate                0.8                           0    bioconda
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.14                          0  
libpng                    1.6.34               he12f830_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_1  
libxml2                   2.9.4                         0  
linecache2                1.0.0            py27hdcabdf0_0  
mappy                     2.10                     py27_1    bioconda
mkl                       2018.0.3                      1  
mkl_fft                   1.0.1            py27h917ab60_0  
mkl_random                1.0.1            py27h78cc56f_0  
mock                      2.0.0                     <pip>
ncurses                   5.9                          10  
numpy                     1.14.5           py27h9bb19eb_0  
numpy-base                1.14.5           py27ha9ae307_0  
ont-tombo                 1.3             py27r341h24bf2e0_1    bioconda
openjdk                   8.0.121                       1  
openssl                   1.0.2o               h26aff7b_0  
pango                     1.40.3                        1  
pbr                       4.0.2                     <pip>
pcre                      8.39                          1  
picard                    2.18.4                   py27_0    bioconda
pip                       10.0.1                   py27_0  
pixman                    0.34.0               hca0a616_3  
protobuf                  3.1.0                     <pip>
pyfaidx                   0.5.3                    py27_0    bioconda
python                    2.7.3                         5  
r-base                    3.4.1                         0  
r-colorspace              1.3_2                  r3.4.1_0  
r-dichromat               2.0_0                  r3.4.1_2  
r-digest                  0.6.12                 r3.4.1_0  
r-ggplot2                 2.2.1                  r3.4.1_0  
r-gridextra               2.2.1                  r3.4.1_0  
r-gtable                  0.2.0                  r3.4.1_0  
r-labeling                0.3                    r3.4.1_2  
r-lazyeval                0.2.0                  r3.4.1_0  
r-magrittr                1.5                    r3.4.1_2  
r-mass                    7.3_47                 r3.4.1_0  
r-munsell                 0.4.3                  r3.4.1_0  
r-plyr                    1.8.4                  r3.4.1_0  
r-rcolorbrewer            1.1_2                  r3.4.1_3  
r-rcpp                    0.12.11                r3.4.1_0  
r-reshape2                1.4.2                  r3.4.1_0  
r-rlang                   0.1.1                  r3.4.1_0  
r-scales                  0.4.1                  r3.4.1_0  
r-stringi                 1.1.5                  r3.4.1_0  
r-stringr                 1.2.0                  r3.4.1_0  
r-tibble                  1.3.3                  r3.4.1_0  
readline                  6.2                           2  
rpy2                      2.8.6              py27r3.4.1_2  
samtools                  1.8                           3    bioconda
scipy                     1.1.0            py27hcaad992_0  
setuptools                39.2.0                   py27_0  
singledispatch            3.4.0.3          py27he22c18d_0  
six                       1.11.0           py27h7252ba3_1  
sqlite                    3.13.0                        0  
tensorflow                0.12.0                    <pip>
tk                        8.6.7                h35a86e2_3  
tqdm                      4.23.4                   py27_0  
traceback2                1.4.0            py27hece0a87_0  
unittest2                 1.1.0            py27hf661856_0  
wheel                     0.31.1                   py27_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               hf3cbc9b_2 
```

I'm very new in this domain, and until now I didn't find any solution.

Can someone help me ?

Thank you
Alex

**Comment by phiweger** [comment]
It seems R and rpy2 are not linked properly.

For me, the following installation worked:

`conda install -c bioconda r rpy2`

You'll then have to reinstall ggplot2.

**Comment by marcus1487** [comment]
Have you tried the suggestions from [this comment](https://github.com/nanoporetech/tombo/issues/29#issuecomment-366248168)? That should help to get the plotting running in a new environment.

**Comment by alexredon** [comment]
I created a new environment and the problem seems to be solved. 

Thanks a lot !
