### ISSUE TITLE
question about plot motif_with_stats

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#89]
Hi:
    When I run `tombo plot motif_with_stats --fast5-basedirs "/home/weir/output/sixrun/col0/workspace/pass/" --statistics-filename sample.de_novo.tombo.stats  --genome-fasta "/home/weir/output/Araport11_genes.201606.cdna.fasta"   --motif  RRACH  --plot-standard-model
`
such error was reported:
`
[17:25:02] Plotting.
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in grid.Call.graphics(L_setviewport, vp, TRUE) :
  INTEGER() can only be applied to a 'integer', not a 'NULL'

  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In addition:
  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Warning messages:

  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 1:
  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In p$widths[2:3] <- maxWidth :
  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:

  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:  number of items to replace is not a multiple of replacement length

  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 2:
  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 3:
  warnings.warn(x, RRuntimeWarning)
/home/weir/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 4:
  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/home/weir/.local/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.3', 'console_scripts', 'tombo')()
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/__main__.py", line 238, in main
    plot_commands._plot_main(args)
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/plot_commands.py", line 2163, in _plot_main
    plot_motif_centered_signif(*base_args, **kwargs)
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/plot_commands.py", line 1927, in plot_motif_centered_signif
    stat_locs, overplot_thresh, pdf_fn, tb_model_fn, alt_model_fn)
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/plot_commands.py", line 1321, in plot_motif_centered_with_stats
    SignalData, BasesData, StatsData, ModelData)
  File "/home/weir/.local/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/home/weir/.local/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in grid.Call.graphics(L_setviewport, vp, TRUE) :
  INTEGER() can only be applied to a 'integer', not a 'NULL'
`

**Comment by marcus1487** [comment]
I can't seem to reproduce this error with my installation. My guess is that this might be a python 2.7/rpy2/R/ggplot2 version issue. I would recommend upgrading to a python3 installation as the rpy2 version for python3 seems to be much more robust and stable.

Were there any warnings earlier in the Tombo output?

**Comment by weir12** [comment]
thanks,all other commands are functioning as normal(e.g:resquiggle,plot genome_location,text_output signif_sequence_context ).there are my software version information:
python 3.6.5
R          3.2.4
rpy2     2.9.1

**Comment by weir12** [comment]
Hi~
      After re-install "ggplot2" packages for R.I try run command above again.
the new error was reported:
 [16:40:01] Loading statistics from file.
[16:40:10] Sorting statistics.
[16:43:04] Parsing Tombo index file(s).
[16:43:13] Parsing Tombo index file(s).
[16:43:29] Finding most signficant regions with motif.
Traceback (most recent call last):
  File "/home/weir/.local/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.3', 'console_scripts', 'tombo')()
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/__main__.py", line 238, in main
    plot_commands._plot_main(args)
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/plot_commands.py", line 2163, in _plot_main
    plot_motif_centered_signif(*base_args, **kwargs)
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/plot_commands.py", line 1873, in plot_motif_centered_signif
    motif.motif_len + context_width - 1, include_pos=True):
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1755, in iter_stat_seqs
    stat_seq = genome_index.get_seq(chrm, start, end)
  File "/home/weir/.local/lib/python2.7/site-packages/tombo/tombo_helper.py", line 385, in get_seq
    'Encountered invalid genome sequence request.')
NotImplementedError: Encountered invalid genome sequence request.

**Comment by weir12** [comment]
Thanks,I'm trying to re-install tombo with `conda install -c bioconda ont-tombo` under anaconda environment.However, an error has occurred when conda check environment:
`Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - ont-tombo
  - r-revoioq
Use "conda info <package>" to see the dependencies for each package.
`
Here are some related information：
R version 3.4.3 
Platform: x86_64-pc-linux-gnu (64-bit)
Microsoft R Open 3.4.3

**Comment by marcus1487** [comment]
My first guess would be to uninstall `r-revoioq` and then try to install tombo again. I don't think `r-revoioq` is required for tombo, so my guess is that this is a package installed separately.
