### ISSUE TITLE
6mA detection fails

### ISSUE THREAD

**Issue by DzmitryGB** [nanoporetech/tombo#90]
Running detect_modifications:
`tombo detect_modifications alternative_model --fast5-basedirs /path/to/fast5s --alternate-bases 6mA --statistics-file-basename sample_alt_model`

Gives the following error (also tried with sudo):
`sh: 0: getcwd() failed: No such file or directory
[17:26:07] Parsing Tombo index file(s).
[17:26:07] Performing alternative model testing.
[17:26:07] Performing alternative model testing against 6mA model.
[17:26:07] Performing modified base detection across genomic regions.
100%|█████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  4.99it/s]
[17:26:08] Saving signal shift significance testing results.
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_stats.py", line 2640, in _get_stats_queue
    stat_type, min_test_reads, alt_name)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_stats.py", line 1624, in write_stats
    with h5py.File(stats_fn, 'w') as stats_fp:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/tmp/pip-nCYoKW-build/h5py/h5f.c:2284)
IOError: Unable to create file (Unable to open file: name = 'sample_alt_model.6ma.tombo.stats', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
^CTraceback (most recent call last):
  File "/usr/local/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.3', 'console_scripts', 'tombo')()
  File "/usr/local/lib/python2.7/dist-packages/tombo/__main__.py", line 203, in main
    tombo_stats._test_shifts_main(args)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_stats.py", line 2905, in _test_shifts_main
    raw_read_coverage)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_stats.py", line 2834, in _test_shifts_alt_main
    alt_name=alt_name)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_stats.py", line 2762, in test_significance
    main_stats_conn.recv()`

Tombo v 1.3, Python 2.7, Ubuntu 18.04

**Comment by marcus1487** [comment]
This looks like a permission issue. Do you have write permission in the output location specified for the tombo stats file?

**Comment by DzmitryGB** [comment]
Apologies - the error is not reproducible. My best guess that it was to do with an updated kernel that failed to load at the next boot.
