### ISSUE TITLE
Error when plot motif_with_stats

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#94]
Hi:
    when I ran `tombo plot motif_with_stats --fast5-basedirs "/home/weir/output/sixrun/col0/workspace/pass/" --motif RRAGH --statistics-filename col0_denovo.tombo.stats --genome-fasta  "/home/weir/output/Araport11_genes.201606.cdna.fasta" --plot-standard-model`
such error has been shown：
 Loading statistics from file.
********************** ERROR ********************
        **Attempt to load statistics file failed. May be an old version of statistics file. Try deleting statistics file and re-calculating using current tombo version.**

I‘m sure that my tombo is latest version and each step is executed in the same environment. Beyond that,I've tried delete old statistics file and run the `Modified Base Detection` again.Unfortunately,this failed to produce the desired result

**Comment by weir12** [comment]
There is a small problem but maybe it's useful:
when I ran ` tombo detect_modifications de_novo --fast5-basedirs "/home/weir/output/sixrun/MTB/workspace/pass/" --statistics-file-basename MTB_denovo --rna --per-read-statistics-basename MTB_denovo_perreads --processes 8`
the program is stuck in this step:
` Saving signal shift significance testing results.`

**Comment by weir12** [comment]
For the second question, this command completely did stall here for several  hours.In addition,two output files size stay at a value(the last modification time of files wasn't changed).

As for the first error,when I entry python and type `import h5py` .The error is shown below:
`/home/weir/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters`
Then I typed `with h5py.File('col0_denovo.tombo.stats', 'r') as stats_fp:
    stats = stats_fp['stats'].value
    stat_type = stats_fp.attrs['stat_type']`
There was another error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weir/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/weir/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-s_7obrrg-build/h5py/h5f.c:2117)
OSError: Unable to open file (File signature not found)`
